services:
  aetherlink:
    image: ghcr.io/hyaeve/aether:latest
    container_name: Aether
    network_mode: host
    volumes:
      - ./config:/config
      - ./data:/data
      # FUSE 读缓存单独映射，建议放到更快的磁盘
      - ./fuse_read_cache:/fuse_read_cache
    environment:
      - TZ=Asia/Shanghai
      - AETHER_PORT=15151
      - AETHER_FUSE_CACHE_DIR=/fuse_read_cache
    devices:
      - /dev/fuse:/dev/fuse
    pid: "host"
    privileged: true
    restart: unless-stopped
