import { test, expect } from '@playwright/test'
import path from 'node:path'

test('file creation, rename confirmation, virtual lists and compact paths', async ({ page }, info) => {
  const storage = { id: 'local', type: 'local', name: '文件测试', enabled: true, config: { root: '/media' } }
  const initial = [
    { id: '/Movies', name: 'Movies', isDir: true, modified: '2026-10-07T10:00:00+08:00' },
    { id: '/one.txt', name: 'one.txt', size: 12, modified: '2026-10-07T10:00:00+08:00' }
  ]
  let entries = [...initial], actions = [], uploads = []
  await page.route('**/api/auth/status', route => route.fulfill({ json: { initialized: true, authenticated: true } }))
  await page.route('**/api/state', route => route.fulfill({ json: {
    username: 'file-test', storages: [storage], tasks: [], settings: {}, cache: {}, traffic: {}, logs: []
  } }))
  await page.route('**/api/files?**', route => {
    const dir = new URL(route.request().url()).searchParams.get('path')
    const files = dir === '/' ? entries : [{ id: `${dir}/next`, name: '下一层很长的目录名称', isDir: true }]
    return route.fulfill({ json: files })
  })
  await page.route('**/api/files/action', route => {
    const data = route.request().postDataJSON()
    actions.push(data)
    if (data.action === 'mkdir') entries.push({ id: `/${data.name}`, name: data.name, isDir: true })
    if (data.action === 'rename') entries = entries.map(f => data.ids.includes(f.id) ? { ...f, name: data.name } : f)
    return route.fulfill({ json: { processed: 1 } })
  })
  await page.route('**/api/files/upload?**', route => {
    uploads.push(new URL(route.request().url()).searchParams.get('name'))
    return route.fulfill({ json: { ok: true } })
  })
  await page.route('**/api/files/offline', route => route.fulfill({ json: { ok: true } }))
  await page.goto('/files')
  await expect(page.getByRole('button', { name: 'Movies', exact: true })).toBeVisible()
  await expect(page.locator('.file-row').first()).toContainText('2026')
  const tabs = await page.locator('.file-tabs').boundingBox()
  const actionsBox = await page.locator('.files-heading-actions').boundingBox()
  expect(Math.abs(tabs.y + tabs.height / 2 - actionsBox.y - actionsBox.height / 2)).toBeLessThan(2)
  await page.getByRole('button', { name: '工具', exact: true }).click()
  await expect(page.getByRole('menuitem')).toHaveText(['新建文件夹', '上传文件', '上传文件夹', '离线下载', '分享转存', '重命名'])
  await page.getByRole('menuitem', { name: '新建文件夹' }).click()
  await expect(page.getByLabel('新名称')).toHaveValue('')
  await page.getByLabel('新名称').press('Enter')
  expect(actions).toHaveLength(0)
  await page.getByRole('button', { name: '工具', exact: true }).click()
  await page.getByRole('menuitem', { name: '新建文件夹' }).click()
  await page.getByLabel('新名称').fill('New Folder')
  await page.locator('.file-view').click({ position: { x: 300, y: 350 } })
  await expect(page.getByRole('button', { name: 'New Folder', exact: true })).toBeVisible()
  expect(actions[0].action).toBe('mkdir')
  await page.getByRole('button', { name: 'one.txt', exact: true }).click()
  await page.keyboard.press('F2')
  await page.getByLabel('新名称').fill('changed.txt')
  await page.locator('.file-view').click({ position: { x: 300, y: 350 } })
  await expect(page.getByRole('dialog', { name: '确认修改名称' })).toBeVisible()
  expect(actions).toHaveLength(1)
  await page.getByRole('button', { name: '确认修改', exact: true }).click()
  await expect(page.getByRole('button', { name: 'changed.txt', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'changed.txt', exact: true }).click({ button: 'right' })
  await expect(page.locator('.context-menu button').last()).toHaveText('查看详情')
  await page.getByRole('button', { name: '查看详情' }).click()
  await expect(page.getByRole('dialog', { name: '文件详情' })).toContainText('changed.txt')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'changed.txt', exact: true }).click()
  await page.keyboard.press('F2')
  await page.getByLabel('新名称').fill('')
  await page.locator('.file-view').click({ position: { x: 300, y: 350 } })
  await expect(page.getByRole('button', { name: 'changed.txt', exact: true })).toBeVisible()
  expect(actions).toHaveLength(2)
  await page.locator('input[type=file]:not([webkitdirectory])').setInputFiles({ name: 'upload.txt', mimeType: 'text/plain', buffer: Buffer.from('upload') })
  await expect.poll(() => uploads).toEqual(['upload.txt'])
  await expect(page.locator('.upload-progress')).toHaveCount(0)
  await page.locator('input[webkitdirectory]').setInputFiles(path.join(process.env.AETHER_E2E_ROOT, 'media', 'Movies'))
  await expect.poll(() => uploads.length).toBe(3)
  expect(uploads.slice(1).every(name => name.startsWith('Movies/'))).toBe(true)
  await expect(page.locator('.upload-progress')).toHaveCount(0)
  await page.getByRole('button', { name: '工具', exact: true }).click()
  await expect(page.getByRole('menuitem', { name: '离线下载' })).toBeEnabled()
  await page.getByRole('button', { name: '工具', exact: true }).click()
  await page.getByRole('button', { name: 'Movies', exact: true }).dblclick()
  for (let i = 0; i < 9; i++) {
    await page.locator('.file-view').getByRole('button', { name: '下一层很长的目录名称', exact: true }).dblclick()
    await expect(page.locator('.path-measure > span')).toHaveCount(i + 2)
    await expect(page.locator('.file-view .file-name')).toBeVisible()
  }
  await expect(page.getByRole('button', { name: '展开省略路径' })).toBeVisible()
  await expect(page.getByRole('navigation', { name: '文件路径' }).getByRole('button', { name: '根目录', exact: true })).toBeVisible()
  await page.getByRole('navigation', { name: '文件路径' }).getByRole('button', { name: '根目录', exact: true }).click()
  entries = Array.from({ length: 2000 }, (_, i) => ({ id: `/file-${i}`, name: `file-${String(i).padStart(4, '0')}.txt`, size: i, isDir: false }))
  await page.getByRole('button', { name: '刷新目录' }).click()
  await expect(page.getByRole('button', { name: 'file-0000.txt', exact: true })).toBeVisible()
  expect(await page.locator('.file-row').count()).toBeLessThan(50)
  await page.locator('.file-view').evaluate(el => { el.scrollTop = el.scrollHeight })
  await expect(page.getByRole('button', { name: 'file-1999.txt', exact: true })).toBeVisible()
  const before = await page.locator('.file-view').evaluate(el => el.scrollHeight)
  await page.locator('.file-view').hover()
  await page.mouse.wheel(0, 2000)
  expect(await page.locator('.file-view').evaluate(el => el.scrollHeight)).toBe(before)
  await page.screenshot({ path: info.outputPath('file-virtual-desktop.png'), fullPage: true })
  await page.getByRole('button', { name: '当前列表视图，切换网格' }).click()
  expect(await page.locator('.file-grid-item').count()).toBeLessThan(100)
  await page.locator('.file-view').evaluate(el => { el.scrollTop = el.scrollHeight })
  await expect(page.getByRole('button', { name: 'file-1999.txt', exact: true })).toBeVisible()
  for (const width of [1440, 1024]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/tasks/strm')
    const heading = await page.locator('.task-heading').boundingBox()
    const button = await page.getByRole('button', { name: '添加任务', exact: true }).boundingBox()
    expect(button.y + button.height).toBeLessThanOrEqual(heading.y + heading.height)
    expect(button.y).toBeLessThan(heading.y + 20)
  }
  entries = entries.map(f => ({ ...f, isDir: true }))
  await page.getByRole('button', { name: '添加任务', exact: true }).click()
  await page.getByRole('button', { name: '选择目录', exact: true }).click()
  await page.getByRole('dialog', { name: '选择存储目录' }).getByRole('button', { name: /文件测试/ }).click()
  await expect(page.locator('.source-directory').first()).toBeVisible()
  expect(await page.locator('.source-directory').count()).toBeLessThan(50)
  await page.locator('.source-list .virtual-directory-list').evaluate(el => { el.scrollTop = el.scrollHeight })
  await expect(page.getByRole('button', { name: 'file-1999.txt', exact: true })).toBeVisible()
  await page.screenshot({ path: info.outputPath('source-virtual.png'), fullPage: true })
  await page.keyboard.press('Escape')
  await page.keyboard.press('Escape')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/files')
  await expect(page.locator('.file-browser')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('file-mobile.png'), fullPage: true })
})
