import { test, expect } from '@playwright/test'

async function setup(page) {
  const png = await page.evaluate(() => {
    const canvas = document.createElement('canvas')
    canvas.width = 1600; canvas.height = 1000
    const ctx = canvas.getContext('2d')
    ctx.fillStyle = '#264b55'; ctx.fillRect(0, 0, 1600, 1000)
    ctx.fillStyle = '#6bbaa5'; ctx.beginPath(); ctx.moveTo(0, 820); ctx.lineTo(670, 230); ctx.lineTo(1110, 820); ctx.fill()
    ctx.fillStyle = '#e6ce83'; ctx.beginPath(); ctx.arc(1240, 220, 90, 0, Math.PI * 2); ctx.fill()
    ctx.fillStyle = '#cee3dd'; ctx.fillRect(0, 820, 1600, 180)
    return canvas.toDataURL('image/png').split(',')[1]
  })
  await page.route('**/viewer-image-*.png', r => r.fulfill({ contentType: 'image/png', body: Buffer.from(png, 'base64') }))
  await page.route('**/api/auth/status', r => r.fulfill({ json: { initialized: true, authenticated: true } }))
  await page.route('**/api/state', r => r.fulfill({ json: { username: 'image-viewer', storages: [{ id: 's', name: '相册', type: 'local', enabled: true, config: {} }], tasks: [], settings: {}, cache: {}, traffic: {} } }))
  await page.route('**/api/files?**', r => r.fulfill({ json: [{ id: '1', name: '01 山与湖.png', url: '/viewer-image-1.png' }, { id: '2', name: '02 第二张.png', url: '/viewer-image-2.png' }, { id: '3', name: '说明.txt' }] }))
  await page.goto('/files')
}

test('image viewer fits, zooms, pans, rotates, navigates and restores focus', async ({ page }, info) => {
  await setup(page)
  await page.getByRole('button', { name: '01 山与湖.png', exact: true }).dblclick()
  const viewer = page.getByRole('dialog', { name: '01 山与湖.png', exact: true })
  await expect(viewer.locator('img')).toHaveClass(/loaded/)
  expect(await viewer.locator('img').evaluate(el => { const r = el.getBoundingClientRect(); return r.left >= 0 && r.top >= 0 && r.right <= innerWidth && r.bottom <= innerHeight })).toBe(true)
  const initial = await viewer.locator('.viewer-scale').textContent()
  await page.getByRole('button', { name: '放大图片', exact: true }).click()
  await expect(viewer.locator('.viewer-scale')).not.toHaveText(initial)
  await page.getByRole('button', { name: '原始尺寸', exact: true }).click()
  await expect(viewer.locator('.viewer-scale')).toHaveText('100%')
  const stage = await viewer.locator('.viewer-stage').boundingBox()
  await page.mouse.move(stage.x + stage.width / 2, stage.y + stage.height / 2)
  await page.mouse.down(); await page.mouse.move(stage.x + stage.width / 2 + 100, stage.y + stage.height / 2 + 60); await page.mouse.up()
  await expect(viewer.locator('img')).toHaveAttribute('style', /translate\(100px, 60px\)/)
  await page.getByRole('button', { name: '旋转图片', exact: true }).click()
  await expect(viewer.locator('img')).toHaveAttribute('style', /rotate\(90deg\)/)
  await page.getByRole('button', { name: '适应窗口', exact: true }).click()
  await expect(page.getByRole('button', { name: '原始尺寸', exact: true })).toBeVisible()
  await viewer.evaluate(async el => { await Promise.allSettled(el.getAnimations({ subtree: true }).map(a => a.finished)) })
  expect(await viewer.locator('img').evaluate(el => { const r = el.getBoundingClientRect(); return r.left >= 0 && r.top >= 0 && r.right <= innerWidth && r.bottom <= innerHeight })).toBe(true)
  await page.screenshot({ path: info.outputPath('viewer-desktop.png') })
  await page.keyboard.press('ArrowRight')
  await expect(page.getByRole('dialog')).toHaveAttribute('aria-label', '02 第二张.png')
  await expect(page.locator('.viewer-counter')).toHaveText('2 / 2')
  await expect(page.locator('.image-viewer img')).toHaveClass(/loaded/)
  await page.keyboard.press('ArrowLeft')
  await expect(page.getByRole('dialog')).toHaveAttribute('aria-label', '01 山与湖.png')
  await page.keyboard.press('Escape')
  await expect(page.locator('.image-viewer')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '01 山与湖.png', exact: true })).toBeFocused()
})

test('thumbnail click opens responsive viewer with keyboard focus contained', async ({ page }, info) => {
  await page.setViewportSize({ width: 390, height: 780 })
  await setup(page)
  await page.getByRole('button', { name: '当前列表视图，切换网格' }).click()
  await page.locator('.file-thumbnail').first().click()
  await expect(page.locator('.image-viewer img')).toHaveClass(/loaded/)
  expect(await page.locator('.viewer-dock').evaluate(el => { const r = el.getBoundingClientRect(); return r.left >= 0 && r.right <= innerWidth })).toBe(true)
  await page.getByRole('button', { name: '下载图片', exact: true }).focus()
  await page.keyboard.press('Tab')
  await expect(page.getByRole('button', { name: '关闭图片预览', exact: true })).toBeFocused()
  await page.evaluate(() => document.documentElement.dataset.theme = 'dark')
  await page.locator('.image-viewer').evaluate(async el => { await Promise.allSettled(el.getAnimations({ subtree: true }).map(a => a.finished)) })
  await page.screenshot({ path: info.outputPath('viewer-mobile-dark.png') })
  await page.getByRole('button', { name: '关闭图片预览', exact: true }).click()
  await expect(page.locator('.image-viewer')).toHaveCount(0)
})

test('Lumic desktop hotspots reveal tools and a stationary click exits without closing after a pan', async ({page}) => {
  await setup(page)
  await page.getByRole('button',{name:'01 山与湖.png',exact:true}).dblclick()
  await expect(page.locator('.image-viewer img.loaded')).toBeVisible()
  await page.mouse.move(500,100)
  await expect(page.locator('.viewer-dock')).toHaveClass(/hidden/)
  const zone=await page.locator('.viewer-dock-zone').boundingBox()
  await page.mouse.move(zone.x+zone.width/2,zone.y+10)
  await expect(page.locator('.viewer-dock')).not.toHaveClass(/hidden/)
  await page.locator('.viewer-dock').getByRole('button',{name:'下一张图片',exact:true}).click()
  await expect(page.locator('.image-viewer')).toHaveAttribute('aria-label','02 第二张.png')
  await page.mouse.move(1400,30)
  await expect(page.locator('.viewer-close')).toHaveCSS('opacity','1')
  const stage=await page.locator('.viewer-stage').boundingBox()
  await page.mouse.move(stage.x+200,stage.y+150);await page.mouse.down();await page.mouse.move(stage.x+250,stage.y+170);await page.mouse.up()
  await page.waitForTimeout(350)
  await expect(page.locator('.image-viewer')).toBeVisible()
  await page.locator('.viewer-stage').click({position:{x:100,y:100}})
  await expect(page.locator('.image-viewer')).toHaveCount(0)
})
