import { test, expect } from '@playwright/test'

async function mock(page) {
  await page.route('**/api/auth/status', r => r.fulfill({ json: { initialized: true, authenticated: true } }))
  await page.route('**/api/state', r => r.fulfill({ json: { username: 'plugin-test', storages: [{ id: 'local', name: '资料', type: 'local', enabled: true, config: {} }], tasks: [], settings: {}, traffic: {}, cache: {}, logs: [], libraryNotices: [{ id: 'new', name: '降临', time: new Date().toISOString() }] } }))
  await page.route('**/api/quark-takeover', r => r.fulfill({ json: { enabled: false, bindings: [] } }))
  await page.route('**/api/files?**', r => r.fulfill({ json: [{ id: '/TOBE', name: 'TOBE', isDir: true }] }))
  const configs = {
    tmdb: { enabled: false, apiURL: 'https://api.themoviedb.org', imageURL: 'https://image.tmdb.org', language: 'zh-CN', apiKey: '' },
    ai: { enabled: false, apiURL: '', model: '', apiKey: '' },
    proxy: { enabled: false, address: '' }, emby: { enabled: false, token: 'random-test-token-123456' }
  }
  await page.route('**/api/plugins/**', r => {
    const [, kind, action] = new URL(r.request().url()).pathname.split('/').slice(2)
    if (action === 'test') return r.fulfill({ json: { ok: true } })
    if (action === 'recognize') return r.fulfill({ json: { result: '标题：降临；年份：2016' } })
    if (action === 'search') return r.fulfill({ json: { result: { results: [{ title: '降临', id: 329865 }] } } })
    if (r.request().method() === 'PUT') configs[kind] = r.request().postDataJSON()
    return r.fulfill({ json: configs[kind] })
  })
  return configs
}

test('TMDB AI proxy and Emby plugins have working forms and actions', async ({ page }, info) => {
  const configs = await mock(page)
  await page.goto('/tools')
  await page.getByRole('button', { name: '启用TMDB 配置', exact: true }).click()
  await page.getByRole('button', { name: 'TMDB 配置', exact: true }).click()
  await expect(page.getByLabel('API 域名', { exact: true })).toHaveValue('https://api.themoviedb.org')
  await expect(page.getByRole('dialog').getByRole('switch')).toHaveCount(0)
  await page.getByLabel('API 密钥', { exact: true }).fill('tmdb-secret')
  await page.getByRole('button', { name: '英文', exact: true }).click()
  await page.getByRole('button', { name: '保存配置', exact: true }).click()
  await expect.poll(() => configs.tmdb.language).toBe('en-US')
  await page.getByRole('button', { name: '测试连接', exact: true }).click()
  await expect(page.locator('.toast').filter({ hasText: '连接成功' })).toBeVisible()
  for (const theme of ['light', 'dark']) {
    await page.evaluate(t => document.documentElement.dataset.theme = t, theme)
    await page.screenshot({ path: info.outputPath(`tmdb-${theme}.png`) })
  }
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'AI 辅助识别', exact: true }).click()
  await expect(page.getByLabel('API 地址', { exact: true })).toHaveValue('')
  await page.getByLabel('API 地址', { exact: true }).fill('https://model.example/v1')
  await page.getByLabel('模型名称', { exact: true }).fill('my-model')
  await page.getByLabel('API Key', { exact: true }).fill('ai-key')
  await page.getByRole('button', { name: '保存配置', exact: true }).click()
  await expect.poll(() => configs.ai.model).toBe('my-model')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '启用AI 辅助识别', exact: true }).click()
  await page.getByRole('button', { name: 'AI 辅助识别', exact: true }).click()
  await expect(page.getByLabel('待识别文件名', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '测试连接', exact: true }).click()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '代理配置', exact: true }).click()
  await page.getByLabel('代理地址', { exact: true }).fill('http://127.0.0.1:7890')
  await page.getByRole('button', { name: '测试连接', exact: true }).click()
  await expect(page.locator('.toast').filter({ hasText: '代理连接成功' })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '启用Emby 入库通知', exact: true }).click()
  await expect.poll(() => configs.emby.enabled).toBe(true)
  await page.getByRole('button', { name: 'Emby 入库通知', exact: true }).getByText('Emby 入库通知', { exact: true }).click()
  await expect(page.locator('.webhook-address')).toContainText('/api/emby/webhook?token=')
  await expect(page.locator('.webhook-help')).toContainText('application/json')
  await page.screenshot({ path: info.outputPath('emby.png') })
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '任务通知', exact: true }).click()
  await expect(page.locator('.notification-dropdown')).toContainText('Emby 入库 · 降临')
})

test('compact cache and rounded grid selection with stable page tabs', async ({ page }, info) => {
  await mock(page)
  await page.goto('/tasks/cache')
  const chart = await page.locator('.cache-chart').boundingBox()
  const progress = await page.locator('.cache-progress').boundingBox()
  const metrics = await page.locator('.cache-metrics').boundingBox()
  expect(chart.width).toBe(104)
  expect(progress.x).toBeGreaterThan(chart.x + chart.width)
  expect(metrics.x).toBeGreaterThan(progress.x + progress.width)
  await expect(page.getByLabel('暂无执行中的缓存任务')).toHaveAttribute('value', '0')
  await page.screenshot({ path: info.outputPath('cache-idle.png') })
  const taskTabs = await page.locator('.content-tabs').boundingBox()
  await page.goto('/files')
  const fileTabs = await page.locator('.file-tabs').boundingBox()
  expect(Math.abs(taskTabs.y - fileTabs.y)).toBeLessThan(2)
  await page.getByRole('button', { name: '当前列表视图，切换网格' }).click()
  await page.getByRole('button', { name: 'TOBE', exact: true }).click()
  await expect(page.locator('.file-grid-item')).toHaveClass(/selected/)
  await expect(page.locator('.file-grid-item')).toHaveCSS('border-radius', '8px')
  await expect(page.locator('.file-grid-name')).toHaveCSS('outline-style', 'none')
  await page.screenshot({ path: info.outputPath('grid-selected.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/tasks/cache')
  expect(await page.locator('.cache-overview').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
})

test('Tianyi QR fills access and refresh tokens without password', async ({ page }, info) => {
  await mock(page)
  await page.route('**/api/authorization/tianyi/start', r => r.fulfill({ json: { token: 'sealed-qr', image: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII=' } }))
  await page.route('**/api/authorization/tianyi/poll', r => r.fulfill({ json: { status: 'success', accessToken: 'access', refreshToken: 'refresh' } }))
  await page.goto('/storage')
  await page.getByRole('button', { name: '添加存储池', exact: true }).click()
  await page.getByRole('button', { name: '天翼云盘', exact: true }).click()
  await page.getByRole('button', { name: '扫码获取 Token', exact: true }).click()
  await expect(page.getByAltText('天翼授权二维码')).toBeVisible()
  await expect(page.getByLabel('访问令牌', { exact: true })).toHaveValue('access', { timeout: 6000 })
  await expect(page.getByLabel('刷新令牌', { exact: true })).toHaveValue('refresh')
  await expect(page.getByLabel('天翼密码', { exact: true })).toHaveCount(0)
  await page.screenshot({ path: info.outputPath('tianyi-token.png') })
})
