import { test, expect } from '@playwright/test'

test('Quark workspace has a binding sidebar, per-account settings and confirmed unbind', async ({ page }, info) => {
  await page.route('**/api/plugins/*', r => r.fulfill({json:{enabled:false}}))
  const storages = ['one','two'].map((id,i) => ({id, name:`夸克 ${i+1}`, type:'quark',enabled:true}))
  let bindings = storages.map(s => ({...s, valid:true,nickname:`账号 ${s.id}`}))
  const configs = Object.fromEntries(storages.map(s => [s.id,{enabled:true, quality:'4k',allowDolby:false,mode:'adaptive',uaListMode:'proxy_list',ua:''}]))
  await page.route('**/api/auth/status', r => r.fulfill({json:{initialized:true,authenticated:true}}))
  await page.route('**/api/state', r => r.fulfill({json:{storages,tasks:[],settings:{},cache:{},traffic:{}}}))
  await page.route('**/api/quark-takeover', r => r.fulfill({json:{enabled:true,bindings}}))
  await page.route('**/api/quark-takeover/*', r => {
    const id = new URL(r.request().url()).pathname.split('/').at(-1)
    if(r.request().method()==='PUT') configs[id]=r.request().postDataJSON()
    if(r.request().method()==='DELETE') bindings=bindings.filter(b=>b.id!==id)
    return r.fulfill({json:{config:configs[id]}})
  })
  await page.goto('/tools')
  await page.getByRole('button',{name:'夸克 STRM 接管',exact:true}).getByText('夸克 STRM 接管',{exact:true}).click()
  const dialog = page.getByRole('dialog',{name:'夸克 STRM 接管',exact:true})
  await expect(dialog.locator('.takeover-account h3')).toHaveText('夸克 1')
  await expect(dialog.getByRole('button',{name:'保存设置',exact:true})).toBeDisabled()
  const left = await dialog.locator('.binding-workspace').boundingBox(), right = await dialog.locator('.takeover-settings').boundingBox()
  expect(left.x+left.width).toBeLessThanOrEqual(right.x+1)
  await dialog.getByRole('button',{name:'接管模式',exact:true}).click()
  await page.getByRole('option',{name:'策略分流',exact:true}).click()
  await dialog.getByRole('button',{name:'直连名单',exact:true}).click()
  await dialog.getByRole('textbox',{name:'UA 关键词',exact:true}).fill('Hills;Infuse')
  await dialog.getByRole('switch',{name:'允许杜比视界',exact:true}).check()
  await dialog.getByRole('button',{name:'保存设置',exact:true}).click()
  await expect.poll(()=>configs.one.ua).toBe('Hills\nInfuse')
  expect(configs.one.uaListMode).toBe('direct_list')
  expect(configs.one.allowDolby).toBe(true)
  for(const theme of ['light','dark']) {
    await page.evaluate(t=>document.documentElement.dataset.theme=t,theme)
    await page.screenshot({path:info.outputPath(`quark-workspace-${theme}.png`)})
  }
  await dialog.getByRole('button',{name:'设置绑定 夸克 2',exact:true}).click()
  await expect(dialog.locator('.takeover-account h3')).toHaveText('夸克 2')
  await expect(dialog.getByRole('button',{name:'接管模式',exact:true})).toHaveText('智能变轨')
  await dialog.getByRole('button',{name:'解除绑定 夸克 2',exact:true}).click()
  await page.getByRole('dialog',{name:'解绑夸克 TV',exact:true}).getByRole('button',{name:'取消',exact:true}).click()
  expect(bindings.length).toBe(2)
  await dialog.getByRole('button',{name:'解除绑定 夸克 2',exact:true}).click()
  await page.getByRole('button',{name:'确认解绑',exact:true}).click()
  await expect(dialog.locator('.binding-row')).toHaveCount(1)
  await page.setViewportSize({width:390,height:844})
  expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth)).toBe(true)
  await page.screenshot({path:info.outputPath('quark-workspace-mobile.png')})
})
