import { test, expect } from '@playwright/test'

async function base(page, libraryNotices=[]) {
  await page.route('**/api/auth/status',r=>r.fulfill({json:{initialized:true,authenticated:true}}))
  await page.route('**/api/state',r=>r.fulfill({json:{username:'scrape-revision',storages:[],tasks:[{id:'t',kind:'strm',name:'作品库'}],settings:{},cache:{},libraryNotices}}))
  await page.route('**/api/plugins/**',r=>r.fulfill({json:{}}))
  await page.route('**/api/quark-takeover',r=>r.fulfill({json:{bindings:[]}}))
}

test('library and playback notices open the specific correlated log',async({page},info)=>{
  await base(page,[{id:'scheduled',name:'月见草🍀 上 Cache file cleanup 已完成',event:'scheduledtasks.completed',time:new Date().toISOString()},
    {id:'playing',libraryName:'月见草🍀',userName:'风信子',series:'刀剑神域',name:'第一集',mediaType:'episode',season:1,episodes:[1],event:'playback.start',time:new Date().toISOString()}])
  await page.route('**/api/logs',r=>r.fulfill({json:[{module:'links',level:'info',time:new Date().toISOString(),message:'Emby 通知 [playing] [playback.start]：刀剑神域'}, {module:'links',level:'info',time:new Date().toISOString(),message:'Emby 通知 [scheduled]：Cache file cleanup'}]}))
  await page.goto('/storage');await page.getByRole('button',{name:'任务通知',exact:true}).click()
  const list=page.locator('.notification-list')
  await expect(list.locator('strong')).toHaveText(['月见草🍀','月见草🍀'])
  await expect(list).toContainText('Cache file cleanup 已完成')
  await expect(list).toContainText('风信子 开始播放 · 刀剑神域 S01E01')
  await expect(list).not.toContainText('电视剧')
  await expect(page.getByRole('button',{name:'清除通知',exact:true})).toHaveCSS('width','22px')
  await page.screenshot({path:info.outputPath('notice.png')})
  await list.getByRole('button').filter({hasText:'风信子'}).click()
  await expect(page).toHaveURL(/\/logs\?/)
  await expect(page.getByRole('textbox',{name:'搜索日志'})).toHaveValue('[playing]')
  await expect(page.locator('.log-entry')).toHaveCount(1)
})

test('scrape selection keeps separated shift ranges, Dock confirms and Esc exits',async({page},info)=>{
  await base(page)
  const items=Array.from({length:12},(_,i)=>({path:`Work${i}/a.strm`,directories:[`Work${i}`],title:`作品${i}`,kind:'movie',status:'pending'}))
  let submitted, matched=false, running=false
  await page.route('**/api/strm-scrape/**',r=>{
    const url=new URL(r.request().url()),action=url.pathname.split('/').at(-1)
    if(action==='items')return r.fulfill({json:items.map((i,n)=>n===0&&matched?{...i,poster:'/aether.svg',status:'ok',tmdb:123}:i)})
    if(action==='directories')return r.fulfill({json:{root:'/media/strm',directories:[]}})
    if(action==='status') {const previous=running;running=false;return r.fulfill({json:{running:false,taskId:'t',message:previous?'刮削完成':''}})}
    if(action==='settings')return r.fulfill({json:{writeMode:'missing'}})
    if(action==='candidates')return r.fulfill({json:[{id:123,title:'候选影片名称很长需要省略并显示完整信息',year:'2026',poster:'/aether.svg'},{id:456,title:'第二部',year:'2020',poster:'/aether.svg'}]})
    if(action==='match'){matched=true;running=true;return r.fulfill({json:{running:true,taskId:'t'}})}
    submitted=r.request().postDataJSON();return r.fulfill({json:action==='reset'?{ok:true}:{running:true,taskId:'t'}})
  })
  await page.goto('/tasks/scrape')
  const cards=page.locator('.scrape-card'), dock=page.getByRole('toolbar',{name:'所选作品操作'})
  await cards.nth(0).click({button:'right',position:{x:20,y:20}})
  await cards.nth(2).getByRole('button',{name:'匹配 作品2',exact:true}).click({modifiers:['Shift']})
  await cards.nth(5).getByRole('button',{name:'匹配 作品5',exact:true}).click()
  await cards.nth(7).getByRole('button',{name:'匹配 作品7',exact:true}).click({modifiers:['Shift']})
  await expect(dock).toContainText('已选 6 项')
  await expect(cards.nth(3)).not.toHaveClass(/selected/);await expect(cards.nth(4)).not.toHaveClass(/selected/)
  await dock.getByRole('button',{name:'清空',exact:true}).click();await expect(dock).toContainText('已选 0 项')
  await dock.getByRole('button',{name:'全选',exact:true}).click();await expect(dock).toContainText('已选 12 项')
  await page.screenshot({path:info.outputPath('dock-desktop.png')})
  await dock.getByRole('button',{name:'重置',exact:true}).click()
  await expect(page.getByRole('dialog',{name:'重置所选作品'})).toContainText('所有非 STRM 文件')
  await page.getByRole('button',{name:'确认重置',exact:true}).click()
  expect(submitted.paths).toHaveLength(12);expect(submitted.deleteFiles).toBe(true);expect(submitted.confirmed).toBe(true)
  await expect(dock).toBeVisible();await page.keyboard.press('Escape');await expect(dock).toHaveCount(0)
  await cards.nth(0).getByRole('button',{name:'匹配 作品0',exact:true}).click()
  const dialog=page.getByRole('dialog',{name:'选择媒体匹配'})
  await expect(dialog.locator('.candidate-card')).toHaveCount(0)
  await expect(dialog).not.toContainText('没有找到候选')
  await dialog.getByRole('button',{name:'搜索候选媒体'}).click()
  await expect(dialog.locator('.candidate-card')).toHaveCount(2)
  await expect(dialog.locator('.candidate-card').first().locator('img')).toHaveCSS('width','72px')
  await dialog.locator('.candidate-card').first().click()
  await expect(dialog.locator('.candidate-card').first()).toHaveAttribute('aria-pressed','true')
  await expect(dialog.locator('.candidate-card').last()).toHaveAttribute('aria-pressed','false')
  await page.mouse.move(20,20)
  await page.screenshot({path:info.outputPath('match-candidates.png')})
  await dialog.getByRole('button',{name:'确认匹配'}).click()
  await expect(cards.first().locator('.scrape-poster img')).toBeVisible({timeout:10000})
  await cards.first().hover();await expect(cards.first().locator('.scrape-actions')).toHaveCSS('opacity','1')
  await page.screenshot({path:info.outputPath('selected-poster.png')})
  await page.setViewportSize({width:390,height:844});await page.evaluate(()=>document.documentElement.dataset.theme='dark')
  await expect(page.getByRole('button',{name:'刷新刮削索引'})).toBeEnabled({timeout:10000})
  await cards.first().click({button:'right',position:{x:20,y:20}})
  await expect(dock).toBeVisible()
  await page.screenshot({path:info.outputPath('dock-mobile.png')})
  await page.getByRole('button',{name:'刷新刮削索引'}).click();await expect(dock).toHaveCount(0)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
})

test('scope tree defaults to all, excludes children and can clear/reinclude ranges',async({page},info)=>{
  await base(page)
  await page.route('**/api/strm-scrape/**',r=>{
    const url=new URL(r.request().url()),action=url.pathname.split('/').at(-1)
    if(action==='items')return r.fulfill({json:[{path:'Show/Season 1/1.strm',directories:['Show/Season 1'],title:'Show',kind:'tv'}]})
    if(action==='directories')return r.fulfill({json:{root:'/data/strm',directories:url.searchParams.get('path')==='Show'?['Show/Season 1','Show/Season 2']:['Show','Movies']}})
    return r.fulfill({json:{running:false}})
  })
  await page.goto('/tasks/scrape');await page.getByRole('button',{name:'筛选库目录'}).click()
  const dialog=page.getByRole('dialog',{name:'刮削范围'})
  await expect(dialog.getByRole('checkbox',{name:'全部目录',exact:true})).toBeChecked()
  await dialog.getByRole('button',{name:'展开 Show',exact:true}).click()
  await dialog.getByRole('checkbox',{name:'Show/Season 1',exact:true}).uncheck()
  await expect(dialog.getByRole('checkbox',{name:'Show/Season 2',exact:true})).toBeChecked()
  await dialog.getByRole('button',{name:'折叠 Show',exact:true}).click()
  await expect(dialog.getByRole('checkbox',{name:'Show/Season 1',exact:true})).toHaveCount(0)
  await dialog.getByRole('button',{name:'展开 Show',exact:true}).click()
  await expect(dialog.getByRole('checkbox',{name:'Show/Season 1',exact:true})).not.toBeChecked()
  await dialog.getByRole('checkbox',{name:'全部目录',exact:true}).check()
  await dialog.getByRole('checkbox',{name:'全部目录',exact:true}).uncheck()
  await expect(dialog.getByRole('checkbox',{name:'Movies',exact:true})).not.toBeChecked()
  await dialog.getByRole('checkbox',{name:'Show/Season 2',exact:true}).check()
  await expect(dialog.getByRole('checkbox',{name:'Show/Season 1',exact:true})).not.toBeChecked()
  await expect(dialog.getByRole('checkbox',{name:'Movies',exact:true})).not.toBeChecked()
  await page.screenshot({path:info.outputPath('scope-tree.png')})
  await dialog.getByRole('checkbox',{name:'全部目录',exact:true}).check()
  await dialog.getByRole('checkbox',{name:'全部目录',exact:true}).uncheck()
  await dialog.getByRole('button',{name:'确认范围',exact:true}).click()
  await expect(page.locator('.scrape-card')).toHaveCount(0)
})
