import { test, expect } from '@playwright/test'

test('STRM scrape workspace scans, rematches and saves settings without shifting tabs', async ({ page }, info) => {
  await page.route('**/api/auth/status', r => r.fulfill({ json: { initialized: true, authenticated: true } }))
  await page.route('**/api/state', r => r.fulfill({ json: { storages: [], tasks: [{ id: 'strm', name: '影片', kind: 'strm' }], settings: {}, traffic: {}, cache: {} } }))
  let progress = { running: false, total: 0, done: 0 }, searches = 0
  let settings = { writeMode: 'missing', episodes: true, fanart: false, actors: false, excluded: '' }
  const items = Array.from({ length: 1000 }, (_, i) => ({ path: `Film${i}.strm`, title: `Film ${i}`, kind: 'movie', status: 'pending', tmdb: 0 }))
  await page.route('**/api/strm-scrape/**', async r => {
    const action = new URL(r.request().url()).pathname.split('/').at(-1)
    if (action === 'items') return r.fulfill({ json: items })
    if (action === 'settings') {
      if (r.request().method() === 'PUT') settings = r.request().postDataJSON()
      return r.fulfill({ json: settings })
    }
    if (action === 'status') return r.fulfill({ json: progress })
    if (action === 'candidates') { searches++; return r.fulfill({json:[{id:123,title:'Film 0',year:'2026',poster:'/aether.svg'}]}) }
    if (action === 'match') {
      const input = r.request().postDataJSON()
      Object.assign(items.find(i => i.path === input.path), { tmdb: input.tmdb, kind: input.kind })
      return r.fulfill({ json: { ok: true } })
    }
    if (action === 'reset') {
      const input = r.request().postDataJSON()
      expect(input.confirmed).toBe(true)
      Object.assign(items.find(i => i.path === input.path), { tmdb: 0, status: 'pending' })
      return r.fulfill({json:{ok:true}})
    }
    const response = { running: true, total: 1000, done: 0, taskId: 'strm' }
    progress = { ...response, running: false, message: '索引已刷新' }
    return r.fulfill({ status: 202, json: response })
  })
  await page.goto('/tasks/cache')
  const before = await page.locator('.content-tabs').boundingBox()
  await page.getByRole('link', { name: 'STRM 刮削', exact: true }).click()
  const after = await page.locator('.content-tabs').boundingBox()
  expect(after.x).toBe(before.x)
  expect(after.y).toBe(before.y)
  await expect(page.getByRole('button', { name: 'STRM 任务', exact: true })).toHaveText('影片')
  await expect(page.locator('.scrape-card').first()).not.toContainText('待匹配')
  await expect(page.locator('.scrape-card').first()).toContainText('电影')
  await expect(page.locator('.scrape-card').first().locator('.work-star')).toHaveAttribute('aria-label','待匹配')
  await expect(page.locator('.scrape-card').first()).toHaveCSS('height','302px')
  expect(await page.locator('.scrape-wall').evaluate(el => getComputedStyle(el).gridTemplateColumns.split(' ').length)).toBe(6)
  await expect(page.getByRole('button', { name: '开始刮削', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '刷新刮削索引', exact: true }).click()
  await expect(page.locator('.scrape-card').first()).toBeVisible()
  expect(await page.locator('.scrape-card').count()).toBeLessThan(100)
  await page.locator('.page-scroll > .thin-scroll-area').evaluate(el => el.scrollTop = el.scrollHeight)
  await expect(page.locator('.scrape-card').last()).toContainText('Film 999')
  expect(await page.locator('.scrape-card').count()).toBeLessThan(100)
  await page.locator('.page-scroll > .thin-scroll-area').evaluate(el => el.scrollTop = 0)
  await expect(page.locator('.scrape-card').first()).toContainText('Film 0')
  await page.locator('.scrape-card').first().hover()
  await page.getByRole('button', { name: '识别作品', exact: true }).first().click()
  await expect(page.locator('.candidate-card')).toHaveCount(0)
  expect(searches).toBe(0)
  await expect(page.locator('.match-source-path')).toContainText('/data/strm/')
  await page.getByRole('button', { name: '搜索候选媒体', exact: true }).click()
  await expect(page.locator('.candidate-card img')).toBeVisible()
  const candidateType = await page.locator('.candidate-search .rounded-select').boundingBox()
  const candidateInput = await page.getByRole('textbox',{name:'候选名称'}).boundingBox()
  expect(candidateType.x + candidateType.width).toBeLessThan(candidateInput.x)
  await page.screenshot({path:info.outputPath('scrape-candidates.png')})
  await page.locator('.candidate-card').click()
  await expect(page.getByLabel('TMDB ID')).toHaveValue('123')
  await page.getByRole('button', { name: '确认匹配', exact: true }).click()
  expect(items[0].tmdb).toBe(123)
  const card = page.locator('.scrape-card').first()
  await card.hover()
  await expect(card.getByRole('button',{name:'重置元数据',exact:true})).toContainText('重置')
  await expect(card.getByRole('button',{name:'识别作品',exact:true})).toContainText('识别')
  await card.evaluate(async el => { await Promise.all(el.getAnimations({subtree:true}).map(a => a.finished.catch(() => {}))) })
  const left = await card.getByRole('button',{name:'重置元数据',exact:true}).boundingBox()
  const right = await card.getByRole('button',{name:'识别作品',exact:true}).boundingBox()
  expect(right.x).toBeGreaterThan(left.x)
  expect(Math.abs(right.width-left.width)).toBeLessThan(1)
  expect(left.width+right.width).toBeGreaterThan((await card.boundingBox()).width-24)
  await expect(card.getByRole('button',{name:'重置元数据',exact:true})).toHaveCSS('border-radius','8px')
  expect(Math.abs(right.y - left.y)).toBeLessThan(1)
  await card.getByRole('button',{name:'重置元数据',exact:true}).click()
  await page.getByRole('button',{name:'确认重置',exact:true}).click()
  expect(items[0].tmdb).toBe(0)
  await page.getByRole('button', { name: '刮削设置', exact: true }).click()
  await expect(page.getByRole('dialog',{name:'STRM 刮削设置'})).toHaveCSS('width','640px')
  await page.getByRole('button', { name: '写入策略', exact: true }).click()
  await page.getByRole('option', { name: '覆盖已有', exact: true }).click()
  await page.getByLabel('背景图', { exact: true }).check()
  await page.getByRole('button', { name: '保存设置', exact: true }).click()
  await expect.poll(() => settings.fanart).toBe(true)
  for (const theme of ['light', 'dark']) {
    await page.evaluate(t => document.documentElement.dataset.theme = t, theme)
    await page.screenshot({ path: info.outputPath(`scrape-${theme}.png`) })
  }
  await page.setViewportSize({width:390,height:844})
  await page.screenshot({path:info.outputPath('scrape-mobile.png')})
  expect(await page.locator('.scrape-panel').evaluate(el=>el.scrollWidth <= el.clientWidth)).toBe(true)
})

test('scrape library selection persists per account and recovers from a deleted task', async ({ page }) => {
  let username = 'scrape-owner'
  let tasks = [{ id: 'one', name: '电影库', kind: 'strm' }, { id: 'two', name: '电视剧库', kind: 'strm' }]
  await page.route('**/api/auth/status', r => r.fulfill({ json: { initialized: true, authenticated: true } }))
  await page.route('**/api/state', r => r.fulfill({ json: { username, storages: [], tasks, settings: {}, traffic: {}, cache: {} } }))
  await page.route('**/api/strm-scrape/**', r => r.fulfill({ json: r.request().url().includes('/items?') ? [] : {} }))
  await page.goto('/tasks/scrape')
  const selector = page.getByRole('button', { name: 'STRM 任务', exact: true })
  await selector.click()
  await page.getByRole('option', { name: '电视剧库', exact: true }).click()
  await page.reload()
  await expect(selector).toHaveText('电视剧库')
  username = 'other'
  await page.reload()
  await expect(selector).toHaveText('电影库')
  username = 'scrape-owner'
  await page.reload()
  await expect(selector).toHaveText('电视剧库')
  tasks = tasks.slice(0, 1)
  await page.reload()
  await expect(selector).toHaveText('电影库')
})
