import { test, expect } from '@playwright/test'

async function mock(page) {
  await page.route('**/api/auth/status', r => r.fulfill({ json: { initialized: true, authenticated: true } }))
  await page.route('**/api/state', r => r.fulfill({ json: { username: 'transfer-test', storages: [{ id: 'local', type: 'local', name: '本地资料', enabled: true, config: {} }], tasks: [], settings: {}, traffic: {}, cache: {} } }))
}

test('transfer modes show actual request records on desktop and mobile', async ({ page }, info) => {
  await mock(page)
  await page.route('**/api/transfers', r => r.fulfill({ json: ['copy', 'download', 'upload'].map((kind, i) => ({ id: kind, kind, name: `${kind}.mkv`, storage: '本地资料', source: i ? 'FUSE' : '浏览器', status: 'running', done: 50, total: 100, started: '2026-10-08T10:10:10Z' })) }))
  await page.goto('/transfer')
  await expect(page.getByRole('link', { name: '传输中心', exact: true })).toBeVisible()
  await expect(page.locator('.transfer-table tbody')).toContainText('copy.mkv')
  await page.getByRole('tab', { name: '上传' }).click()
  await expect(page.locator('.transfer-table tbody')).toContainText('upload.mkv')
  await expect(page.locator('.transfer-table tbody')).not.toContainText('download.mkv')
  await page.screenshot({ path: info.outputPath('transfers-desktop.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  const tabs = await page.getByRole('tab').all()
  const boxes = await Promise.all(tabs.map(t => t.boundingBox()))
  expect(boxes.every(b => b.y === boxes[0].y)).toBe(true)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('transfers-mobile.png') })
  await page.getByRole('link', { name: '备份规则', exact: true }).click()
  await expect(page.getByText('暂无备份规则', { exact: true })).toBeVisible()
})

test('extension presets toggle normalized groups and blank tools menu follows pointer', async ({ page }, info) => {
  await mock(page)
  await page.route('**/api/files?**', r => r.fulfill({ json: [] }))
  await page.goto('/files')
  const view = page.locator('.file-view')
  const box = await view.boundingBox()
  await view.click({ button: 'right', position: { x: 80, y: 100 } })
  const menu = page.getByRole('menu')
  await expect(menu).toBeVisible()
  await expect.poll(async () => Math.abs((await menu.boundingBox()).x - box.x - 80)).toBeLessThan(2)
  await expect.poll(async () => Math.abs((await menu.boundingBox()).y - box.y - 100)).toBeLessThan(2)
  await page.keyboard.press('Escape')
  await page.goto('/tasks/strm')
  await page.getByRole('button', { name: '添加任务', exact: true }).click()
  const media = page.locator('#task-media-extensions'), metadata = page.locator('#task-metadata-extensions')
  await page.getByRole('button', { name: '音频扩展名', exact: true }).click()
  await page.getByRole('button', { name: '视频扩展名', exact: true }).click()
  await expect(media).toHaveValue(/opus;mp4/)
  await expect(page.getByRole('button', { name: '视频扩展名', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '音频扩展名', exact: true }).click()
  await expect(media).not.toHaveValue(/mp3/)
  await page.getByRole('button', { name: '数据扩展名', exact: true }).click()
  await page.getByRole('button', { name: '图片扩展名', exact: true }).click()
  await expect(metadata).toHaveValue('nfo;ass;srt;jpg;jpeg;png;webp')
  const m = await media.boundingBox(), d = await metadata.boundingBox()
  expect(m.x).toBe(d.x); expect(m.width).toBe(d.width); expect(d.y).toBeGreaterThan(m.y + m.height)
  await page.screenshot({ path: info.outputPath('extensions-desktop.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.getByRole('dialog').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.screenshot({ path: info.outputPath('extensions-mobile.png') })
})
