import { test, expect } from '@playwright/test'

test('file alignment, ED2K tab, mount metadata and virtual playback', async ({ page }, info) => {
  const storages = [{ id: 'local', type: 'local', name: '本机资料', enabled: true, config: {} }]
  const events = Array.from({ length: 2000 }, (_, i) => ({ time: '2026-10-07T15:00:00+08:00', upstream: 'library', outcome: 'redirect', target: `https://example.com/file-${i}`, userAgent: `Player ${i}`, client: '2001:db8::1', durationMs: 123 }))
  await page.route('**/api/auth/status', r => r.fulfill({ json: { initialized: true, authenticated: true } }))
  await page.route('**/api/state', r => r.fulfill({ json: { username: 'polish', storages, tasks: [], settings: {}, cache: {}, traffic: {}, logs: [] } }))
  await page.route('**/api/files?**', r => r.fulfill({ json: [{ id: '/book', name: 'Book', isDir: true }] }))
  await page.route('**/api/links', r => r.fulfill({ json: [{ id: 'library', name: '四字上游', type: 'emby', enabled: true }] }))
  await page.route('**/api/link-playback', r => r.fulfill({ json: { recentEvents: events } }))
  await page.route('**/api/mounts', r => r.fulfill({ json: [{ id: 'm', name: '媒体盘', mountPoint: '/NetDisk', storageId: 'local', sourceLabel: '根目录', uid: 0, gid: 0, mode: 493, status: 'mounted' }] }))
  await page.goto('/files')
  await page.getByRole('button', { name: '展开收藏栏' }).click()
  await expect(page.locator('.file-favorites')).toHaveCSS('opacity', '1')
  await expect.poll(async () => {
    const select = await page.locator('.file-toolbar > .rounded-select').boundingBox()
    const favorites = await page.locator('.file-favorites').boundingBox()
    return Math.abs(select.x + select.width - favorites.x - favorites.width)
  }).toBeLessThan(2)
  await page.getByRole('button', { name: 'Book', exact: true }).click({ button: 'right' })
  await page.locator('.context-menu').getByRole('button', { name: '删除', exact: true }).click()
  await expect(page.locator('.confirmation-backdrop')).toHaveCSS('backdrop-filter', 'none')
  expect((await page.getByRole('dialog').boundingBox()).width).toBeLessThanOrEqual(420)
  await page.keyboard.press('Escape')
  await page.goto('/tasks/ed2k')
  await expect(page.getByRole('link', { name: 'ED2K 任务' })).toHaveClass(/active/)
  await page.getByRole('button', { name: '添加任务', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '添加 ED2K 任务' })).toBeVisible()
  await page.keyboard.press('Escape')
  await page.goto('/files/mounts')
  await expect(page.locator('.mount-card')).toContainText('/NetDisk/AetherDrive')
  await expect(page.locator('.mount-card')).toContainText('UID 0 · GID 0 · 0755')
  await page.screenshot({ path: info.outputPath('mount-details.png') })
  await page.goto('/links/cache')
  await expect(page.locator('.playback-count')).toHaveText('共 2000 条')
  expect(await page.locator('.playback-event').count()).toBeLessThan(50)
  await page.locator('.playback-scroller').evaluate(el => { el.scrollTop = el.scrollHeight })
  await expect(page.locator('.playback-event').last()).toContainText('Player 1999')
  await page.screenshot({ path: info.outputPath('playback-virtual.png') })
})
