import { test, expect } from '@playwright/test'
import path from 'node:path'
import { readFileSync } from 'node:fs'
import { createMeteorBatch, meteorOpacity } from '../src/meteor.js'

test('meteor batches contain two to five upper-right to lower-left trails', () => {
  for (const value of [0, .25, .5, .999999]) {
    const batch = createMeteorBatch(() => value)
    expect(batch).toHaveLength(2 + Math.floor(value * 4))
    for (const meteor of batch) {
      expect(meteor.x).toBeGreaterThanOrEqual(1 / 3)
      expect(meteor.x).toBeLessThanOrEqual(1)
      expect(meteor.y).toBeLessThan(.24)
      expect(meteor.distance).toBeGreaterThanOrEqual(.65)
      expect(meteor.distance).toBeLessThanOrEqual(1)
      expect(meteor.fadeStart).toBeGreaterThanOrEqual(1 / 3)
      expect(meteor.duration).toBeGreaterThanOrEqual(1.8)
      expect(meteor.duration).toBeLessThanOrEqual(7.8)
      expect(meteor.tail).toBeGreaterThanOrEqual(.04)
      expect(meteor.tail).toBeLessThanOrEqual(.065)
      expect(meteorOpacity(1 / 3, meteor.fadeStart, meteor.fadeEnd)).toBe(1)
      expect(meteorOpacity(meteor.fadeEnd, meteor.fadeStart, meteor.fadeEnd)).toBe(0)
    }
  }
  expect(meteorOpacity(0)).toBe(0)
  expect(meteorOpacity(1)).toBe(0)
  expect(meteorOpacity(.1)).toBeLessThan(meteorOpacity(.2))
  expect(meteorOpacity(.5)).toBeGreaterThan(meteorOpacity(.75))
  expect(meteorOpacity(.75)).toBeGreaterThan(meteorOpacity(.95))
  expect(createMeteorBatch(() => 0)[0].duration).toBe(1.8)
  expect(createMeteorBatch(() => .5)[0].duration).toBe(4.4)
  expect(createMeteorBatch(() => .999)[0].duration).toBeGreaterThan(7)
})

test('storage, STRM, cache, themes and responsive workspace', async ({ page }, testInfo) => {
  const errors = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '建立你的以太空间' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('login-desktop.png'), fullPage: true })
  await expect(page.getByLabel('账号', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('密码', { exact: true })).toHaveValue('')
  await page.getByLabel('账号', { exact: true }).fill('my-aether-owner')
  await page.getByLabel('密码', { exact: true }).fill('a1')
  await page.getByRole('button', { name: '创建管理员账号' }).click()
  await expect(page.locator('.breadcrumbs strong')).toHaveText('存储管理')
  await expect(page.getByRole('navigation', { name: '主导航' }).getByRole('link')).toHaveCount(9)
  await expect(page.locator('.sidebar a[href]')).toHaveCount(0)
  await expect(page.locator('.storage-actions')).toHaveCount(0)
  await expect(page.locator('.breadcrumbs')).toContainText('存储管理')
  expect(await page.locator('.topbar').evaluate(el => el.getBoundingClientRect().height)).toBe(48)
  expect(await page.locator('.nav-group button').last().evaluate(el => innerHeight - el.getBoundingClientRect().bottom)).toBeLessThan(55)
  await expect(page.locator('.workspace-switch, .sidebar-foot, .supported-section')).toHaveCount(0)
  await page.screenshot({ path: testInfo.outputPath('storage-empty-desktop.png'), fullPage: true })
  await page.getByRole('button', { name: '添加存储池', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('storage-picker-desktop.png'), fullPage: true })
  await page.getByRole('dialog').getByRole('button', { name: /本机存储/ }).click()
  await page.getByLabel('存储池名称').fill('本地影音库')
  await page.getByLabel('本地根目录').fill(path.join(process.env.AETHER_E2E_ROOT, 'media'))
  await expect(page.getByLabel('删除模式')).toHaveValue('trash')
  await page.getByRole('button', { name: '保存存储池' }).click()
  await expect(page.getByRole('heading', { name: '本地影音库', exact: true })).toBeVisible()
  await expect(page.getByText('待验证', { exact: true })).toHaveCount(0)
  expect(await page.locator('.storage-grid').evaluate(el => {
    const card = el.querySelector('.storage-card').getBoundingClientRect(), add = el.querySelector('.add-storage-tile').getBoundingClientRect()
    return card.width === add.width && card.height === add.height
  })).toBe(true)
  await expect(page.locator('.storage-card footer')).toHaveCount(0)
  await page.getByRole('button', { name: '存储操作 本地影音库', exact: true }).click()
  await expect(page.locator('.storage-menu button')).toHaveText(['编辑存储', '测试连接', '删除存储'])
  await page.screenshot({ path: testInfo.outputPath('storage-menu-desktop.png'), fullPage: true })
  await page.keyboard.press('Escape')
  await expect(page.locator('.storage-menu')).toHaveCount(0)
  await page.getByRole('button', { name: '存储操作 本地影音库', exact: true }).click()
  await page.getByRole('button', { name: '测试连接', exact: true }).click()
  await expect(page.getByText('连接正常', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('storage-desktop.png'), fullPage: true })

  await page.getByRole('button', { name: '存储操作 本地影音库', exact: true }).click()
  await page.getByRole('button', { name: '删除存储', exact: true }).click()
  await expect(page.getByRole('dialog', { name: '删除存储池', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '取消', exact: true }).click()
  await page.getByRole('button', { name: '存储操作 本地影音库', exact: true }).click()
  await page.getByRole('button', { name: '编辑存储', exact: true }).click()
  await page.getByLabel('存储池名称').fill('家庭影音库')
  await page.getByRole('button', { name: '保存存储池' }).click()
  await expect(page.getByRole('heading', { name: '家庭影音库', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '停用存储池 家庭影音库', exact: true }).click()
  await expect(page.getByRole('button', { name: '启用存储池 家庭影音库', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '启用存储池 家庭影音库', exact: true }).click()
  await expect(page.getByRole('button', { name: '停用存储池 家庭影音库', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '文件服务', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Movies', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Movies', exact: true }).click()
  await expect(page.getByText('Arrival.MP4', { exact: true })).toBeVisible()

  await page.getByRole('link', { name: '任务管理', exact: true }).click()
  await expect(page.getByRole('link', { name: 'STRM 任务', exact: true })).toHaveClass(/active/)
  const tabY = await page.locator('.task-heading .content-tabs').evaluate(el => el.getBoundingClientRect().top)
  const actionY = await page.getByRole('button', { name: '添加任务', exact: true }).evaluate(el => el.getBoundingClientRect().top)
  expect(Math.abs(tabY - actionY)).toBeLessThan(20)
  await expect(page.getByRole('navigation', { name: '任务栏目' }).getByRole('link')).toHaveCount(5)
  await page.getByRole('button', { name: '添加任务', exact: true }).click()
  await page.getByLabel('任务名称').fill('电影增量同步')
  await page.getByRole('button', { name: '选择目录', exact: true }).click()
  await page.getByRole('dialog', { name: '选择存储目录' }).getByRole('button', { name: 'Movies', exact: true }).click()
  await page.getByRole('button', { name: '选择当前目录', exact: true }).click()
  await expect(page.getByLabel('生成目录')).toHaveValue('')
  await page.getByRole('button', { name: '更多选项', exact: true }).click()
  await page.getByLabel('排除文件', { exact: true }).fill('sample')
  await page.screenshot({ path: testInfo.outputPath('strm-dialog-desktop.png'), fullPage: true })
  await page.getByRole('button', { name: '保存任务', exact: true }).click()
  await expect(page.getByText('电影增量同步', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '立即执行', exact: true }).click()
  await expect(page.getByText('已完成', { exact: true })).toBeVisible({ timeout: 20000 })
  const strm = readFileSync(path.join(process.env.AETHER_E2E_ROOT, 'data', 'strm', 'Arrival.MP4.strm'), 'utf8')
  expect(strm).toMatch(/^http:\/\/[^/]+:15159\/stream\//)
  expect(strm).toContain('?sign=')
  await page.screenshot({ path: testInfo.outputPath('tasks-desktop.png'), fullPage: true })
  await expect(page.locator('.notification-badge')).toHaveText('1')
  await page.getByRole('button', { name: '任务通知', exact: true }).click()
  await expect(page.locator('.notification-dropdown')).toContainText('电影增量同步')
  await expect(page.locator('.notification-badge')).toHaveCount(0)
  await page.keyboard.press('Escape')

  await page.getByRole('link', { name: '缓存任务', exact: true }).click()
  await page.getByRole('button', { name: '添加任务', exact: true }).click()
  await page.getByLabel('任务名称').fill('目录预热')
  await expect(page.getByLabel('API 间隔', { exact: true })).toHaveValue('200')
  await expect(page.getByLabel('执行间隔', { exact: true })).toHaveValue('60')
  await page.getByRole('button', { name: '保存任务', exact: true }).click()
  await expect(page.getByText('目录预热', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '缓存设置', exact: true }).click()
  await expect(page.getByLabel('全局缓存时间', { exact: true })).toBeVisible()
  await expect(page.getByLabel('全局缓存时间', { exact: true })).toHaveValue('30')
  await expect(page.getByLabel('缓存条目上限', { exact: true })).toHaveValue('10000')
  await expect(page.getByLabel('缓存内存上限', { exact: true })).toHaveValue('128')
  const cacheControl = page.locator('.number-control').filter({ has: page.getByLabel('全局缓存时间', { exact: true }) })
  await cacheControl.hover()
  await expect(cacheControl.locator('.number-unit')).toHaveCSS('opacity', '0')
  await page.getByRole('button', { name: '增加全局缓存时间', exact: true }).click()
  await expect(page.getByLabel('全局缓存时间', { exact: true })).toHaveValue('31')
  await page.getByLabel('全局缓存时间', { exact: true }).focus()
  expect(await cacheControl.evaluate(el => getComputedStyle(el).boxShadow)).toContain('inset')
  expect(await page.getByLabel('全局缓存时间', { exact: true }).evaluate(el => getComputedStyle(el).outlineStyle)).toBe('none')
  await page.getByLabel('全局缓存时间', { exact: true }).fill('45')
  await page.getByRole('button', { name: '保存设置', exact: true }).click()
  await page.reload()
  await expect(page.getByLabel('全局缓存时间', { exact: true })).toHaveValue('45')
  await page.screenshot({ path: testInfo.outputPath('cache-settings-desktop.png'), fullPage: true })
  await expect(page.locator('.theme-toggle')).toHaveCount(1)
  await page.getByRole('button', { name: '主题：日光', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.screenshot({ path: testInfo.outputPath('cache-settings-dark.png'), fullPage: true })
  await page.getByRole('button', { name: '主题：夜间', exact: true }).click()
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')

  await page.getByRole('button', { name: '账号菜单', exact: true }).click()
  await page.getByRole('button', { name: '账号设置', exact: true }).click()
  await expect(page.getByRole('navigation', { name: '系统设置栏目' })).toContainText('账号与安全')
  await expect(page.getByLabel('当前密码', { exact: true })).toHaveCount(0)
  await expect(page.getByLabel('会话有效期', { exact: true })).toHaveValue('7')
  await expect(page.getByRole('link', { name: '常规设置', exact: true })).toHaveCount(0)
  await page.getByLabel('密码', { exact: true }).fill('a1')
  await page.getByLabel('会话有效期', { exact: true }).fill('14')
  await page.getByRole('button', { name: '保存账号', exact: true }).click()
  await expect(page.getByText('账号已更新，其他会话已退出', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('会话有效期', { exact: true })).toHaveValue('14')
  await page.screenshot({ path: testInfo.outputPath('account-settings-desktop.png'), fullPage: true })
  await expect(page.getByLabel('账号', { exact: true })).toHaveValue('my-aether-owner')
  await page.goto('/storage')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator('.breadcrumbs strong')).toHaveText('存储管理')
  await expect(page.locator('.sidebar')).not.toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('storage-mobile.png'), fullPage: true })
  await page.setViewportSize({ width: 375, height: 812 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '添加存储池', exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('storage-picker-mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '打开导航', exact: true }).click()
  await page.getByRole('link', { name: '系统日志', exact: true }).click()
  await expect(page.locator('.breadcrumbs strong')).toHaveText('系统日志')
  await page.getByRole('button', { name: '账号菜单', exact: true }).click()
  await page.getByRole('button', { name: '退出登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '欢迎回到以太' })).toBeVisible()
  await page.getByLabel('账号', { exact: true }).fill('my-aether-owner')
  await page.getByLabel('密码', { exact: true }).fill('a1')
  await page.getByRole('button', { name: '登录工作空间', exact: true }).click()
  await expect(page.locator('.breadcrumbs strong')).toHaveText('系统日志')
  await page.getByRole('button', { name: '账号菜单', exact: true }).click()
  await page.getByRole('button', { name: '退出登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '欢迎回到以太' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('login-mobile.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('compact storage authorization, about and plugin views', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByLabel('账号', { exact: true }).fill('my-aether-owner')
  await page.getByLabel('密码', { exact: true }).fill('a1')
  await page.getByRole('button', { name: '登录工作空间', exact: true }).click()
  await expect(page.getByRole('navigation', { name: '主导航' })).toBeVisible()
  await page.goto('/storage')
  await page.getByRole('button', { name: '添加存储池', exact: true }).click()
  await expect(page.locator('.wizard-steps')).toHaveCount(0)
  await page.getByRole('dialog').getByRole('button', { name: '115 网盘', exact: true }).click()
  await expect(page.getByLabel('删除模式')).toHaveValue('trash')
  await page.screenshot({ path: testInfo.outputPath('storage-115-desktop.png'), fullPage: true })
  expect(await page.getByRole('dialog').evaluate(el => el.scrollHeight <= el.clientHeight)).toBe(true)
  await page.context().route('https://example.com/authorize', route => route.fulfill({ contentType: 'text/html', body: '<title>115 Authorization Test</title>' }))
  await page.route('**/api/authorization/115/start', route => {
    expect(route.request().postDataJSON().base).toBe('https://oauth.litepan.top')
    return route.fulfill({ json: { token: 'mock-session', url: 'https://example.com/authorize', expiresIn: 300 } })
  })
  await page.route('**/api/authorization/115/poll', route => route.fulfill({ json: { status: 'success', accessToken: 'test-access', refreshToken: 'test-refresh' } }))
  const popupPromise = page.waitForEvent('popup')
  await page.getByRole('button', { name: '获取 TOKEN', exact: true }).click()
  const popup = await popupPromise
  await expect(popup).toHaveURL('https://example.com/authorize')
  await expect(page.getByRole('link', { name: '打开授权页面', exact: true })).toHaveAttribute('href', 'https://example.com/authorize')
  await expect(page.getByLabel('Access Token', { exact: false })).toHaveValue('test-access')
  await page.getByRole('button', { name: '上一步', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '夸克网盘', exact: true }).click()
  await page.route('**/api/authorization/quark/start', route => route.fulfill({ json: { token: 'mock-qr', image: '/aether.svg', expiresIn: 300 } }))
  await page.route('**/api/authorization/quark/poll', route => route.fulfill({ json: { status: 'success', cookie: '__pus=test; __puus=test' } }))
  await page.getByRole('button', { name: '扫码获取授权', exact: true }).click()
  await expect(page.getByAltText('夸克授权二维码')).toBeVisible()
  await expect(page.getByLabel('Cookie')).toHaveValue('__pus=test; __puus=test')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: testInfo.outputPath('storage-quark-mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('button', { name: '账号菜单', exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('account-menu.png'), fullPage: true })
  await page.getByRole('button', { name: '关于以太', exact: true }).click()
  const accountTab = page.getByRole('link', { name: '账号与安全', exact: true })
  const beforeTabWidth = await accountTab.evaluate(el => el.getBoundingClientRect().width)
  await accountTab.click()
  expect(await accountTab.evaluate(el => el.getBoundingClientRect().width)).toBe(beforeTabWidth)
  expect(await page.locator('.account-settings').evaluate(el => el.clientWidth)).toBeLessThanOrEqual(380)
  expect(await page.locator('.account-settings').evaluate(el => {
    const fields = [...el.querySelectorAll('.credential-input, .number-control')].map(n => n.getBoundingClientRect())
    return fields.every(r => r.height === fields[0].height && r.width === fields[0].width)
  })).toBe(true)
  await expect(accountTab).toHaveCSS('border-radius', '0px')
  await page.getByRole('link', { name: '关于以太', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Aether 以太', exact: true })).toBeVisible()
  await expect(page.getByText('当前版本 v0.1.0', { exact: true })).toBeVisible()
  await page.route('**/api/version/check', route => route.fulfill({ json: { current: '0.1.0', latest: 'v0.2.0', available: true, message: '发现新版本，请更新容器镜像' } }))
  await page.getByRole('button', { name: '检查更新', exact: true }).click()
  const updateToast = page.locator('.toast').filter({ hasText: '发现新版本' })
  await expect(updateToast).toBeVisible()
  await expect(updateToast).toHaveCSS('opacity', '1')
  await expect(updateToast).toHaveCSS('border-left-width', '4px')
  await expect(page.locator('.about-copy [role=status]')).toHaveCount(0)
  await expect(page.locator('.about-page .satellite')).toHaveCount(7)
  const satellite = page.locator('.about-page .satellite').first()
  const satellitePosition = await satellite.evaluate(el => el.style.transform)
  await expect.poll(() => satellite.evaluate(el => el.style.transform)).not.toBe(satellitePosition)
  await page.screenshot({ path: testInfo.outputPath('update-toast-desktop.png'), fullPage: true })
  await expect(updateToast).toHaveCount(0, { timeout: 7000 })
  const frame = await page.locator('.about-page .starfield').evaluate(el => el.toDataURL())
  await expect.poll(() => page.locator('.about-page .starfield').evaluate(el => el.toDataURL())).not.toBe(frame)
  await expect(page.locator('.about-page .gravity-well')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('about-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.locator('.about-page .login-universe')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('about-mobile.png'), fullPage: true })
  expect(await page.locator('.about-actions').evaluate(el => el.getBoundingClientRect().top > document.querySelector('.about-copy').getBoundingClientRect().bottom)).toBe(true)
  await page.route('**/api/version/check', route => route.fulfill({ json: { current: '0.1.0', latest: '0.1.0', available: false, revision: 'same', message: '当前镜像与 GHCR latest 一致' } }))
  await page.getByRole('button', { name: '检查更新', exact: true }).click()
  await expect(page.locator('.toast').filter({ hasText: '当前版本已是最新' })).toBeVisible()
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('link', { name: '辅助工具', exact: true }).click()
  await expect(page.locator('.plugin-card')).toHaveCount(10)
  expect(await page.locator('.plugin-grid').evaluate(el => getComputedStyle(el).gridTemplateColumns.split(' ').length)).toBe(4)
  await page.screenshot({ path: testInfo.outputPath('plugins-desktop.png'), fullPage: true })
  await page.getByRole('button', { name: /识别规则/ }).click()
  await expect(page.getByRole('dialog')).toContainText('最小视频、整理黑名单、自定义识别词、自定义匹配')
})

test('native mobile CAS task creation and persistence', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByLabel('账号', { exact: true }).fill('my-aether-owner')
  await page.getByLabel('密码', { exact: true }).fill('a1')
  await page.getByRole('button', { name: '登录工作空间', exact: true }).click()
  await expect(page.getByRole('navigation', { name: '主导航' })).toBeVisible()
  await page.getByRole('link', { name: '存储管理', exact: true }).click()
  await page.getByRole('button', { name: '添加存储池', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '移动云盘', exact: true }).click()
  await expect(page.getByRole('combobox', { name: '接入方式', exact: true })).toHaveCount(0)
  await page.getByLabel('存储池名称').fill('CAS 测试个人云')
  await page.getByLabel('Authorization', { exact: false }).fill(Buffer.from('pc:13900000000:test-token').toString('base64'))
  await page.getByRole('button', { name: '保存存储池', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'CAS 测试个人云', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '任务管理', exact: true }).click()
  await page.getByRole('link', { name: 'CAS 任务', exact: true }).click()
  await expect(page.getByRole('navigation', { name: '任务栏目' }).locator('.active')).toHaveText('CAS 任务')
  await expect(page.getByText('尚未实现', { exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '添加任务', exact: true }).click()
  await page.getByLabel('任务名称').fill('CAS 电影库')
  await expect(page.getByLabel('还原文件保留时间', { exact: true })).toHaveValue('12')
  await page.getByLabel('还原文件保留时间', { exact: true }).fill('24')
  await expect(page.getByLabel('API 间隔', { exact: true })).toHaveValue('200')
  await page.getByLabel('Cron 表达式').fill('0 3 * * *')
  await page.getByLabel('生成目录').fill('cas-movies')
  await page.route('**/api/files?**', route => route.fulfill({ json: [{ id: 'movies-dir', name: 'Movies', isDir: true }] }))
  await page.getByRole('button', { name: '选择目录', exact: true }).click()
  await expect(page.locator('.source-accounts button')).toHaveCount(1)
  await page.getByRole('dialog', { name: '选择存储目录' }).getByRole('button', { name: 'Movies', exact: true }).click()
  await page.getByRole('button', { name: '选择当前目录', exact: true }).click()
  await page.getByRole('button', { name: '更多选项', exact: true }).click()
  await page.getByLabel('排除类型').fill('ISO;avi')
  await page.screenshot({ path: testInfo.outputPath('cas-task-desktop.png'), fullPage: true })
  await page.getByRole('button', { name: '保存任务', exact: true }).click()
  await expect(page.getByText('CAS 电影库', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByText('CAS 电影库', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '编辑任务', exact: true }).click()
  await expect(page.getByLabel('Cron 表达式')).toHaveValue('0 3 * * *')
  await expect(page.getByLabel('还原文件保留时间', { exact: true })).toHaveValue('24')
  await expect(page.locator('.source-trigger')).toContainText('movies-dir')
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '临时文件', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'CAS 临时文件' })).toContainText('默认 12 小时')
  await page.getByRole('button', { name: '清理过期项', exact: true }).click()
  await expect(page.getByText('已清理 0 个过期临时文件', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: testInfo.outputPath('cas-tasks-mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('native Tianyi account storage and CAS task', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByLabel('账号', { exact: true }).fill('my-aether-owner')
  await page.getByLabel('密码', { exact: true }).fill('a1')
  await page.getByRole('button', { name: '登录工作空间', exact: true }).click()
  await expect(page.getByRole('navigation', { name: '主导航' })).toBeVisible()
  await page.getByRole('link', { name: '存储管理', exact: true }).click()
  await page.getByRole('button', { name: '添加存储池', exact: true }).click()
  await page.getByRole('dialog').getByRole('button', { name: '天翼云盘', exact: true }).click()
  await expect(page.getByLabel('OpenList 服务地址', { exact: false })).toHaveCount(0)
  await page.getByLabel('存储池名称').fill('CAS 天翼个人云')
  await page.getByLabel('天翼账号', { exact: true }).fill('18900000000')
  await page.getByLabel('天翼密码', { exact: true }).fill('mock-secret')
  await expect(page.getByLabel('根目录 ID')).toHaveValue('-11')
  await page.screenshot({ path: testInfo.outputPath('tianyi-storage-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: testInfo.outputPath('tianyi-storage-mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: '保存存储池', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'CAS 天翼个人云', exact: true })).toBeVisible()
  const state = await (await page.request.get('/api/state')).json()
  const pool = state.storages.find(s => s.name === 'CAS 天翼个人云')
  expect(pool.config.password).toBe('********')
  expect(pool.config.mode).toBe('native')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('link', { name: '任务管理', exact: true }).click()
  await page.getByRole('link', { name: 'CAS 任务', exact: true }).click()
  await page.getByRole('button', { name: '添加任务', exact: true }).click()
  await page.getByLabel('任务名称').fill('天翼 CAS 电影库')
  await expect(page.getByLabel('还原文件保留时间', { exact: true })).toHaveValue('12')
  await page.route('**/api/files?**', route => route.fulfill({ json: [{ id: '12345', name: '天翼电影', isDir: true }] }))
  await page.getByRole('button', { name: '选择目录', exact: true }).click()
  await expect(page.locator('.source-accounts button')).toHaveCount(2)
  await page.locator('.source-accounts').getByRole('button', { name: /CAS 天翼个人云/ }).click()
  await page.screenshot({ path: testInfo.outputPath('source-picker-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: testInfo.outputPath('source-picker-mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByLabel('筛选当前目录文件夹').fill('不存在')
  await expect(page.locator('.source-directory')).toHaveCount(0)
  await page.getByLabel('筛选当前目录文件夹').fill('')
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('dialog', { name: '选择存储目录' }).getByRole('button', { name: '天翼电影', exact: true }).click()
  await page.getByRole('button', { name: '选择当前目录', exact: true }).click()
  await page.getByRole('button', { name: '保存任务', exact: true }).click()
  await expect(page.getByText('天翼 CAS 电影库', { exact: true })).toBeVisible()
  await page.reload()
  const row = page.getByRole('row').filter({ hasText: '天翼 CAS 电影库' })
  await row.getByRole('button', { name: '编辑任务', exact: true }).click()
  await expect(page.locator('.source-trigger')).toContainText('CAS 天翼个人云')
  await expect(page.locator('.source-trigger')).toContainText('12345')
  await page.screenshot({ path: testInfo.outputPath('tianyi-cas-desktop.png'), fullPage: true })
})

test('WebDAV users and scoped directories', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByLabel('账号', { exact: true }).fill('my-aether-owner')
  await page.getByLabel('密码', { exact: true }).fill('a1')
  await page.getByRole('button', { name: '登录工作空间', exact: true }).click()
  await expect(page.getByRole('navigation', { name: '主导航' })).toBeVisible()
  await expect(page.getByRole('link', { name: '仪表盘', exact: true }).locator('svg')).toHaveClass(/lucide-gauge/)
  await page.getByRole('link', { name: '文件服务', exact: true }).click()
  await expect(page.getByRole('navigation', { name: '文件服务栏目' }).getByRole('link')).toHaveCount(3)
  await expect(page.getByRole('link', { name: '文件管理', exact: true })).toHaveClass(/active/)
  await page.getByRole('link', { name: '本地挂载', exact: true }).click()
  await expect(page.locator('.breadcrumbs strong')).toHaveText('文件服务')
  await page.getByRole('link', { name: 'WebDAV', exact: true }).click()
  await expect(page).toHaveURL(/\/files\/webdav$/)
  await page.goto('/webdav')
  await expect(page).toHaveURL(/\/files\/webdav$/)
  await expect(page.getByRole('link', { name: 'WebDAV', exact: true }).locator('.dav-symbol')).toHaveText('DAV')
  await expect(page.getByRole('button', { name: '保存设置', exact: true })).toHaveCount(0)
  const serviceSwitch = page.getByRole('switch', { name: /启用 WebDAV 服务/ })
  await serviceSwitch.check()
  await expect(serviceSwitch).toBeEnabled()
  await page.reload()
  await expect(serviceSwitch).toBeChecked()
  await page.getByLabel('外部访问地址', { exact: true }).fill('http://192.168.1.20:15151')
  await page.getByLabel('外部访问地址', { exact: true }).blur()
  await expect(page.getByLabel('外部访问地址', { exact: true })).toBeEnabled()
  await page.reload()
  await expect(page.getByLabel('外部访问地址', { exact: true })).toHaveValue('http://192.168.1.20:15151')
  await page.getByRole('button', { name: '添加用户', exact: true }).click()
  await page.getByLabel('账号', { exact: true }).fill('media-reader')
  await page.getByLabel('密码', { exact: true }).fill('reader-secret')
  await page.getByRole('button', { name: '添加目录', exact: true }).click()
  await page.locator('.source-accounts').getByRole('button', { name: /家庭影音库/ }).click()
  await page.getByRole('dialog', { name: '选择存储目录' }).getByRole('button', { name: 'Movies', exact: true }).click()
  await page.getByRole('button', { name: '选择当前目录', exact: true }).click()
  await page.getByLabel('目录显示名称').fill('Movies')
  await page.screenshot({ path: testInfo.outputPath('webdav-user-desktop.png'), fullPage: true })
  await page.getByRole('button', { name: '保存用户', exact: true }).click()
  await expect(page.locator('.dav-users')).toContainText('media-reader')
  await page.getByRole('button', { name: '停用用户', exact: true }).click()
  await expect(page.getByRole('button', { name: '启用用户', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '启用用户', exact: true }).click()
  await expect(page.getByRole('button', { name: '停用用户', exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('webdav-cards-desktop.png'), fullPage: true })
  await page.getByRole('button', { name: '编辑用户', exact: true }).click()
  await expect(page.getByLabel('密码', { exact: true })).toHaveValue('')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: testInfo.outputPath('webdav-user-mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: '保存用户', exact: true }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.getByRole('link', { name: '文件管理', exact: true }).click()
  await expect(page.getByRole('button', { name: '刷新目录', exact: true })).toHaveText('')
  expect(await page.locator('.file-toolbar .search-field').evaluate(el => el.previousElementSibling.getAttribute('aria-label'))).toBe('刷新目录')
  await page.getByRole('link', { name: '辅助工具', exact: true }).click()
  await expect(page.locator('.plugin-description')).toHaveCount(10)
  await expect(page.locator('.plugin-description').first()).toHaveCSS('text-overflow', 'ellipsis')
  await page.screenshot({ path: testInfo.outputPath('tools-descriptions.png'), fullPage: true })
})

test('log filters, isolated refresh and virtual scrolling', async ({ page }, testInfo) => {
  const errors = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await page.getByLabel('账号', { exact: true }).fill('my-aether-owner')
  await page.getByLabel('密码', { exact: true }).fill('a1')
  await page.getByRole('button', { name: '登录工作空间', exact: true }).click()
  await expect(page.locator('.sidebar')).toBeVisible()
  let requests = 0
  await page.route('**/api/logs', route => {
    requests++
    return route.fulfill({ json: Array.from({ length: 1500 }, (_, i) => ({ time: new Date(2026, 9, 4, 10, 0, i).toISOString(), level: i % 2 ? 'error' : 'warn', module: i % 2 ? 'tasks' : 'storage', message: `事件 ${i} · ${'目录扫描已完成，缓存数据已保存。'.repeat(i % 5 + 1)}` })) })
  })
  await page.getByRole('link', { name: '系统日志', exact: true }).click()
  await expect(page.locator('.log-panel footer')).toHaveText('1500 条记录')
  expect(await page.locator('.log-entry').count()).toBeLessThan(50)
  await page.locator('.log-viewport').evaluate(el => { el.scrollTop = 25000 })
  await expect(page.locator('.log-entry').first()).not.toContainText('事件 1499')
  await page.getByLabel('日志级别').selectOption('error')
  await page.getByLabel('日志模块').selectOption('tasks')
  await page.getByLabel('搜索日志').fill('事件 149')
  await expect(page.locator('.log-panel footer')).toHaveText('6 条记录')
  await expect(page.locator('.log-view-toggle')).toHaveText('')
  await expect(page.locator('.topbar button[title], .log-toolbar button[title]')).toHaveCount(0)
  await expect(page.getByLabel('日志级别')).toHaveCSS('border-radius', '12px')
  await expect(page.locator('.log-view-toggle svg')).toHaveClass(/lucide-table-properties/)
  await page.getByRole('button', { name: '当前结构化列表，切换原始列表', exact: true }).click()
  await expect(page.locator('.log-view-toggle svg')).toHaveClass(/lucide-logs/)
  await page.reload()
  await expect(page.getByLabel('日志级别')).toHaveValue('error')
  await expect(page.getByLabel('日志模块')).toHaveValue('tasks')
  await expect(page.getByLabel('搜索日志')).toHaveValue('事件 149')
  await expect(page.locator('.log-entry.raw')).toHaveCount(6)
  const before = requests
  await page.getByRole('button', { name: '刷新日志', exact: true }).click()
  await expect.poll(() => requests).toBe(before + 1)
  await page.screenshot({ path: testInfo.outputPath('logs-raw-desktop.png'), fullPage: true })
  await page.getByRole('button', { name: '当前原始列表，切换结构化列表', exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('logs-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('logs-mobile.png'), fullPage: true })
  expect(await page.getByLabel('日志级别').evaluate(el => el.clientWidth)).toBeGreaterThan(100)
  expect(await page.getByLabel('日志模块').evaluate(el => el.clientWidth)).toBeGreaterThan(90)
  await page.locator('.log-view-toggle').click()
  await expect(page.locator('.log-entry.raw').first()).toBeVisible()
  await expect.poll(() => page.locator('.log-entry.raw').first().evaluate(el => el.getBoundingClientRect().height)).toBeGreaterThan(88)
  expect(await page.locator('.log-viewport').evaluate(el => el.scrollWidth <= el.clientWidth)).toBe(true)
  await page.getByLabel('搜索日志').clear()
  await page.getByLabel('日志级别').selectOption('all')
  await page.getByLabel('日志模块').selectOption('all')
  expect(await page.locator('.log-entry.raw').count()).toBeLessThan(50)
  await page.screenshot({ path: testInfo.outputPath('logs-raw-mobile.png'), fullPage: true })
  await page.locator('.log-viewport').evaluate(el => { el.scrollTop = el.scrollHeight })
  await expect(page.locator('.log-entry.raw').last()).toContainText('事件 0 ·')
  expect(await page.locator('.log-entry.raw').evaluateAll(rows => rows.every((row, i) => !i || row.getBoundingClientRect().top >= rows[i - 1].getBoundingClientRect().bottom - 1))).toBe(true)
  expect(errors).toEqual([])
})

test('login starfield, orbit motion and provider assets', async ({ page }, testInfo) => {
  const errors = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await expect(page.locator('.login-page')).toBeVisible()
  const logos = page.locator('.satellite .provider-logo')
  await expect(logos).toHaveCount(5)
  await expect.poll(() => logos.evaluateAll(images => images.every(img => img.complete && img.naturalWidth > 0))).toBe(true)
  const starPixels = () => page.locator('.starfield').evaluate(canvas => {
    const { data } = canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height)
    let lit = 0
    for (let i = 3; i < data.length; i += 4) if (data[i] > 0) lit++
    return lit
  })
  expect(await starPixels()).toBeGreaterThan(500)
  const first = page.locator('.satellite').first()
  const position = await first.evaluate(el => el.style.transform)
  await expect.poll(() => first.evaluate(el => el.style.transform)).not.toBe(position)
  await expect(page.locator('.universe-motion')).toHaveCount(0)
  const canvasFrame = () => page.locator('.starfield').evaluate(canvas => canvas.toDataURL())
  const initialFrame = await canvasFrame()
  await expect.poll(canvasFrame).not.toBe(initialFrame)
  const logoStyles = await page.locator('.satellite .provider-icon').first().evaluate(el => {
    const css = getComputedStyle(el)
    return { background: css.backgroundColor, border: css.borderWidth, shadow: css.boxShadow }
  })
  expect(logoStyles).toEqual({ background: 'rgba(0, 0, 0, 0)', border: '0px', shadow: 'none' })
  await expect(page.locator('.satellite-name')).toHaveCount(0)
  await expect(page.locator('.satellite-framed')).toHaveCount(3)
  await expect(page.locator('.satellite-framed .provider-icon').first()).toHaveCSS('border-radius', '25%')
  expect(await page.locator('.gravity-well').evaluate(canvas => {
    const { data } = canvas.getContext('2d').getImageData(0, 0, canvas.width, canvas.height)
    let filled = 0
    for (let i = 3; i < data.length; i += 4) if (data[i] > 20) filled++
    return filled
  })).toBeGreaterThan(500)
  expect(await page.locator('[data-provider="openlist"] .provider-icon').evaluate(el => getComputedStyle(el).padding)).toBe('1px')
  for (const provider of ['openlist', 'webdav', 'local']) {
    expect(await page.locator(`[data-provider="${provider}"] .provider-icon`).evaluate(el => getComputedStyle(el).backgroundColor)).toBe('rgb(255, 255, 255)')
  }
  await expect(page.locator('[data-provider="tianyi"] img')).toHaveAttribute('src', '/providers/tianyi.png')
  await expect(page.locator('[data-provider="webdav"] .dav-symbol')).toHaveText('DAV')
  await expect(page.locator('[data-provider="local"] svg')).toHaveClass(/lucide-cloud-download/)
  expect(await page.locator('[data-provider="tianyi"] img').evaluate(img => img.naturalWidth)).toBeGreaterThan(100)
  const username = page.getByLabel('账号', { exact: true })
  await username.focus()
  expect(await username.evaluate(el => getComputedStyle(el).outlineStyle)).toBe('none')
  expect(await username.evaluate(el => getComputedStyle(el.parentElement).boxShadow)).toContain('inset')
  await expect(page.locator('.login-form label')).toHaveCount(0)
  await expect(page.locator('.login-form-side > footer')).toHaveCount(0)
  expect(await page.locator('.credential-input').evaluateAll(nodes => nodes[0].clientHeight === nodes[1].clientHeight && nodes[0].clientWidth === nodes[1].clientWidth)).toBe(true)
  const password = page.getByLabel('密码', { exact: true })
  await password.fill('test')
  expect(await password.evaluate(el => getComputedStyle(el).outlineStyle)).toBe('none')
  expect(await page.locator('.login-form .input-action').evaluate(el => getComputedStyle(el).boxShadow)).toContain('inset')
  await expect(password).toHaveAttribute('type', 'password')
  await expect(page.getByRole('button', { name: '显示密码' }).locator('svg')).toHaveClass(/lucide-eye-off/)
  await page.getByRole('button', { name: '显示密码' }).click()
  await expect(password).toHaveAttribute('type', 'text')
  await expect(page.getByRole('button', { name: '隐藏密码' }).locator('svg')).toHaveClass(/lucide-eye-icon/)
  await page.getByRole('button', { name: '隐藏密码' }).click()
  await expect(password).toHaveAttribute('type', 'password')
  await password.clear()
  await password.focus()
  await page.screenshot({ path: testInfo.outputPath('login-stars-desktop.png'), fullPage: true })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(page.locator('.login-universe')).toHaveClass(/motion-paused/)
  const reducedPosition = await first.evaluate(el => el.style.transform)
  await page.waitForTimeout(250)
  expect(await first.evaluate(el => el.style.transform)).toBe(reducedPosition)

  for (const width of [1920, 1024, 768, 390, 375]) {
    await page.setViewportSize({ width, height: width > 760 ? 900 : 844 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
    expect(await page.evaluate(() => document.documentElement.scrollHeight <= window.innerHeight)).toBe(true)
    if (width > 760) {
      await expect(page.locator('.login-universe')).toBeVisible()
      // Wait for ResizeObserver to lay out the complete orbital scene.
      await expect.poll(() => page.locator('.satellite-body').evaluateAll(nodes => {
        const panel = document.querySelector('.login-universe').getBoundingClientRect()
        return nodes.every(el => {
          const r = el.getBoundingClientRect()
          return r.left >= panel.left && r.right <= panel.right && r.top >= panel.top && r.bottom <= panel.bottom
        })
      })).toBe(true)
      expect(await starPixels()).toBeGreaterThan(500)
    } else {
      await expect(page.locator('.login-universe')).not.toBeVisible()
      await expect(page.getByRole('button', { name: '登录工作空间', exact: true })).toBeVisible()
    }
    await page.screenshot({ path: testInfo.outputPath(`login-stars-${width}.png`), fullPage: true })
  }
  expect(errors).toEqual([])
})
