import { test, expect } from '@playwright/test'
import path from 'node:path'
import { readFileSync } from 'node:fs'

test('storage, STRM, cache, themes and responsive workspace', async ({ page }, testInfo) => {
  const errors = []
  page.on('pageerror', e => errors.push(e.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: '建立你的以太空间' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('login-desktop.png'), fullPage: true })
  await expect(page.getByLabel('账户名', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('密码', { exact: true })).toHaveValue('')
  await page.getByLabel('账户名', { exact: true }).fill('my-aether-owner')
  await page.getByLabel('密码', { exact: true }).fill('e2e-password-123456')
  await page.getByRole('button', { name: '创建管理员账户' }).click()
  await expect(page.getByRole('heading', { name: '存储管理.' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('storage-empty-desktop.png'), fullPage: true })
  await page.getByRole('button', { name: '添加存储池', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('storage-picker-desktop.png'), fullPage: true })
  await page.getByRole('dialog').getByRole('button', { name: /本机存储/ }).click()
  await page.getByLabel('存储池名称').fill('本地影音库')
  await page.getByLabel('本地根目录').fill(path.join(process.env.AETHER_E2E_ROOT, 'media'))
  await page.getByRole('button', { name: '保存存储池' }).click()
  await expect(page.getByRole('heading', { name: '本地影音库', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '测试连接', exact: true }).click()
  await expect(page.getByText('连接正常', { exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('storage-desktop.png'), fullPage: true })

  await page.getByRole('button', { name: '编辑存储池', exact: true }).click()
  await page.getByLabel('存储池名称').fill('家庭影音库')
  await page.getByRole('button', { name: '保存存储池' }).click()
  await expect(page.getByRole('heading', { name: '家庭影音库', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '浏览文件', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Movies', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Movies', exact: true }).click()
  await expect(page.getByText('Arrival.MP4', { exact: true })).toBeVisible()

  await page.getByRole('link', { name: 'STRM 任务', exact: true }).click()
  await page.getByRole('button', { name: '添加任务', exact: true }).click()
  await page.getByLabel('任务名称').fill('电影增量同步')
  await page.getByRole('button', { name: '选择目录', exact: true }).click()
  await page.getByRole('dialog', { name: '选择存储目录' }).getByRole('button', { name: 'Movies', exact: true }).click()
  await page.getByRole('button', { name: '选择当前目录', exact: true }).click()
  await expect(page.getByLabel('本地生成目录')).toHaveValue('')
  await page.getByRole('button', { name: '更多选项', exact: true }).click()
  await page.getByLabel('排除文件', { exact: true }).fill('sample')
  await page.screenshot({ path: testInfo.outputPath('strm-dialog-desktop.png'), fullPage: true })
  await page.getByRole('button', { name: '保存任务', exact: true }).click()
  await expect(page.getByText('电影增量同步', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '立即执行', exact: true }).click()
  await expect(page.getByText('已完成', { exact: true })).toBeVisible({ timeout: 20000 })
  const strm = readFileSync(path.join(process.env.AETHER_E2E_ROOT, 'data', 'strm', 'Arrival.MP4.strm'), 'utf8')
  expect(strm).toContain('http://localhost:15151/stream/')
  expect(strm).toContain('?sign=')
  await page.screenshot({ path: testInfo.outputPath('tasks-desktop.png'), fullPage: true })

  await page.getByRole('link', { name: '缓存任务', exact: true }).click()
  await page.getByRole('button', { name: '添加任务', exact: true }).click()
  await page.getByLabel('任务名称').fill('目录预热')
  await expect(page.getByLabel('API 间隔')).toHaveValue('200')
  await expect(page.getByLabel('执行间隔')).toHaveValue('60')
  await page.getByRole('button', { name: '保存任务', exact: true }).click()
  await expect(page.getByText('目录预热', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '缓存设置', exact: true }).click()
  await expect(page.getByRole('heading', { name: '缓存设置.' })).toBeVisible()
  await expect(page.getByLabel('全局缓存时间')).toHaveValue('30')
  await expect(page.getByLabel('缓存条目上限')).toHaveValue('10000')
  await expect(page.getByLabel('缓存内存上限')).toHaveValue('128')
  await page.getByLabel('全局缓存时间').fill('45')
  await page.getByRole('button', { name: '保存设置', exact: true }).click()
  await page.reload()
  await expect(page.getByLabel('全局缓存时间')).toHaveValue('45')
  await page.screenshot({ path: testInfo.outputPath('cache-settings-desktop.png'), fullPage: true })
  await page.getByRole('button', { name: '夜间', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await page.screenshot({ path: testInfo.outputPath('cache-settings-dark.png'), fullPage: true })
  await page.getByRole('button', { name: '系统', exact: true }).click()
  await page.emulateMedia({ colorScheme: 'light' })
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light')

  await page.getByRole('button', { name: '账户菜单', exact: true }).click()
  await page.getByRole('button', { name: '账户设置', exact: true }).click()
  await expect(page.getByRole('heading', { name: '账户与安全', exact: true })).toBeVisible()
  await expect(page.getByLabel('账户名', { exact: true })).toHaveValue('my-aether-owner')
  await page.goto('/storage')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('heading', { name: '存储管理.' })).toBeVisible()
  await expect(page.locator('.sidebar')).not.toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('storage-mobile.png'), fullPage: true })
  await page.setViewportSize({ width: 375, height: 812 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '添加存储池', exact: true }).click()
  await page.screenshot({ path: testInfo.outputPath('storage-picker-mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: '关闭', exact: true }).click()
  await page.getByRole('button', { name: '打开导航', exact: true }).click()
  await page.getByRole('link', { name: '系统日志', exact: true }).click()
  await expect(page.getByRole('heading', { name: '系统日志.' })).toBeVisible()
  await page.getByRole('button', { name: '账户菜单', exact: true }).click()
  await page.getByRole('button', { name: '退出登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '欢迎回到以太' })).toBeVisible()
  await page.getByLabel('账户名', { exact: true }).fill('my-aether-owner')
  await page.getByLabel('密码', { exact: true }).fill('e2e-password-123456')
  await page.getByRole('button', { name: '登录工作空间', exact: true }).click()
  await expect(page.getByRole('heading', { name: '系统日志.' })).toBeVisible()
  await page.getByRole('button', { name: '账户菜单', exact: true }).click()
  await page.getByRole('button', { name: '退出登录', exact: true }).click()
  await expect(page.getByRole('heading', { name: '欢迎回到以太' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('login-mobile.png'), fullPage: true })
  expect(errors).toEqual([])
})
