import { test, expect } from '@playwright/test'
import { createServer } from 'node:net'

async function port() {
  const server = createServer()
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
  const value = server.address().port
  await new Promise(resolve => server.close(resolve))
  return value
}
test('link configuration, modes, activation, playback and log preferences', async ({ page }, info) => {
  await page.goto('/')
  await page.getByLabel('账号', { exact: true }).fill('my-aether-owner')
  await page.getByLabel('密码', { exact: true }).fill('a1')
  await page.getByRole('button', { name: '登录工作空间', exact: true }).click()
  await expect(page.locator('.sidebar')).toBeVisible()
  await page.getByRole('link', { name: '以太链接', exact: true }).click()
  await page.getByRole('button', { name: '添加以太链接', exact: true }).click()
  await expect(page.locator('.link-type-picker button')).toHaveCount(3)
  await page.getByRole('button', { name: 'Emby', exact: true }).click()
  await page.getByLabel('以链名称', { exact: true }).fill('客厅 Emby')
  await page.getByLabel('服务地址', { exact: true }).fill('http://127.0.0.1:15998')
  await page.getByLabel('反代端口', { exact: true }).fill(String(await port()))
  await page.getByLabel('API Key', { exact: true }).fill('test-secret')
  await page.getByText('更多选项', { exact: true }).click()
  await page.getByLabel('屏蔽 UA', { exact: true }).fill('blocked-test\nanother-client')
  await page.getByRole('button', { name: '保存以链', exact: true }).click()
  await expect(page.locator('.link-card')).toHaveCount(1)
  await page.getByRole('button', { name: '客厅 Emby跳转模式', exact: true }).click()
  await page.getByRole('option', { name: '公网跳转', exact: true }).click()
  await expect(page.getByRole('button', { name: '客厅 Emby跳转模式', exact: true })).toHaveText('公网跳转')
  await page.getByRole('button', { name: '停用以链 客厅 Emby', exact: true }).click()
  await expect(page.getByRole('button', { name: '启用以链 客厅 Emby', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.locator('.link-card')).toHaveCount(1)
  await page.getByRole('button', { name: '编辑以链 客厅 Emby', exact: true }).click()
  await expect(page.getByLabel('API Key', { exact: true })).toHaveValue('********')
  await page.getByText('更多选项', { exact: true }).click()
  await expect(page.getByLabel('屏蔽 UA', { exact: true })).toHaveValue('blocked-test\nanother-client')
  await page.keyboard.press('Escape')
  await page.screenshot({ path: info.outputPath('links-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: info.outputPath('links-mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('link', { name: '直链缓存', exact: true }).click()
  await expect(page.getByText('暂无播放记录', { exact: true })).toBeVisible()
  await page.goto('/settings/logs')
  await expect(page.getByLabel('日志保留天数', { exact: true })).toHaveValue('15')
  await expect(page.getByLabel('日志条数上限', { exact: true })).toHaveValue('20000')
  await page.getByLabel('日志保留天数', { exact: true }).fill('20')
  await page.getByRole('button', { name: '保存设置', exact: true }).click()
  await expect(page.locator('.toast').filter({ hasText: '设置已保存' })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('日志保留天数', { exact: true })).toHaveValue('20')
  await page.goto('/files')
  await expect(page.getByRole('button', { name: 'Movies', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Movies', exact: true }).dblclick()
  await page.getByRole('button', { name: '展开收藏栏', exact: true }).click()
  await page.getByRole('button', { name: '收藏当前目录', exact: true }).click()
  await expect(page.getByRole('complementary', { name: '目录收藏' })).toContainText('Movies')
  await page.getByRole('navigation', { name: '文件路径' }).getByRole('button', { name: '根目录', exact: true }).click()
  await page.getByRole('complementary', { name: '目录收藏' }).getByRole('button', { name: 'Movies', exact: true }).click()
  await page.getByRole('button', { name: '当前列表视图，切换网格', exact: true }).click()
  await expect(page.locator('.file-grid-item')).toHaveCount(2)
  await page.screenshot({ path: info.outputPath('files-grid-mobile.png'), fullPage: true })
  await page.reload()
  await expect(page.getByRole('button', { name: '当前网格视图，切换列表', exact: true })).toBeVisible()
  await page.getByRole('complementary', { name: '目录收藏' }).getByRole('button', { name: 'Movies', exact: true }).click()
  await expect(page.locator('.file-grid-item')).toHaveCount(2)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: info.outputPath('files-grid-desktop.png'), fullPage: true })
  await page.goto('/tools')
  await page.getByRole('button', { name: /^配置备份/ }).click()
  await expect(page.getByRole('dialog')).toContainText('密码加密')
  await page.getByRole('button', { name: '导出配置备份', exact: true }).click()
  await page.getByLabel('备份密码', { exact: true }).fill('backup-test')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: '确认导出', exact: true }).click()
  expect((await download).suggestedFilename()).toMatch(/^aether-config-.*\.aether$/)
})
