import { test, expect } from '@playwright/test'
import { createServer } from 'node:net'

async function port() {
  const server = createServer()
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
  const value = server.address().port
  await new Promise(resolve => server.close(resolve))
  return value
}
test('link configuration, modes, activation, playback and log preferences', async ({ page }, info) => {
  await page.goto('/')
  await page.getByLabel('账号', { exact: true }).fill('my-aether-owner')
  await page.getByLabel('密码', { exact: true }).fill('a1')
  await page.getByRole('button', { name: '登录工作空间', exact: true }).click()
  await expect(page.locator('.sidebar')).toBeVisible()
  await page.getByRole('link', { name: '以太链接', exact: true }).click()
  await page.getByRole('button', { name: '添加以太链接', exact: true }).click()
  await expect(page.locator('.link-type-picker button')).toHaveCount(3)
  await page.getByRole('button', { name: 'Emby', exact: true }).click()
  await page.getByLabel('以链名称', { exact: true }).fill('客厅 Emby')
  await page.getByLabel('服务地址', { exact: true }).fill('http://127.0.0.1:15998')
  await page.getByLabel('反代端口', { exact: true }).fill(String(await port()))
  await page.getByLabel('API Key', { exact: true }).fill('test-secret')
  await page.getByText('更多选项', { exact: true }).click()
  await page.getByLabel('屏蔽 UA', { exact: true }).fill('blocked-test\nanother-client')
  await page.getByRole('button', { name: '保存以链', exact: true }).click()
  await expect(page.locator('.link-card')).toHaveCount(1)
  await expect(page.locator('.link-identity')).toHaveCSS('padding-left', '6px')
  await page.getByRole('button', { name: '客厅 Emby跳转模式', exact: true }).click()
  await page.getByRole('option', { name: '公网跳转', exact: true }).click()
  await expect(page.getByRole('button', { name: '客厅 Emby跳转模式', exact: true })).toHaveText('公网跳转')
  await page.getByRole('button', { name: '停用以链 客厅 Emby', exact: true }).click()
  await expect(page.getByRole('button', { name: '启用以链 客厅 Emby', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.locator('.link-card')).toHaveCount(1)
  await page.getByRole('button', { name: '以链操作 客厅 Emby', exact: true }).click()
  await page.getByRole('button', { name: '编辑以链', exact: true }).click()
  await expect(page.getByLabel('API Key', { exact: true })).toHaveValue('*'.repeat('test-secret'.length))
  const secretBox = await page.getByLabel('API Key', { exact: true }).boundingBox()
  await page.getByRole('button', { name: '显示内容', exact: true }).click()
  await expect(page.getByLabel('API Key', { exact: true })).toHaveAttribute('type', 'text')
  await expect(page.getByLabel('API Key', { exact: true })).toHaveValue('test-secret')
  expect(await page.getByLabel('API Key', { exact: true }).boundingBox()).toEqual(secretBox)
  await page.getByRole('button', { name: '隐藏内容', exact: true }).click()
  await expect(page.getByLabel('API Key', { exact: true })).toHaveValue('*'.repeat('test-secret'.length))
  await page.getByRole('button', { name: '显示内容', exact: true }).click()
  await expect(page.getByLabel('API Key', { exact: true })).toHaveValue('test-secret')
  await page.getByText('更多选项', { exact: true }).click()
  await expect(page.getByLabel('屏蔽 UA', { exact: true })).toHaveValue('blocked-test\nanother-client')
  await page.keyboard.press('Escape')
  await expect(page.locator('.link-grid')).toHaveCSS('grid-template-columns', /(?:\d+(?:\.\d+)?px\s+){3}\d+(?:\.\d+)?px/)
  await page.route('**/api/link-playback', route => route.fulfill({ json: { recentEvents: [
    { time: new Date().toISOString(), upstream: 'test', mediaPath: 'redirect-book.m4b', outcome: 'redirect', client: 'ios' },
    { time: new Date().toISOString(), upstream: 'test', mediaPath: 'proxy-book.wma', outcome: 'transcode', client: 'ios' }
  ] } }))
  await page.getByRole('link', { name: '直链缓存', exact: true }).click()
  await expect(page).toHaveURL(/\/links\/cache$/)
  await page.reload()
  await expect(page.locator('.link-playback')).toBeVisible()
  await expect(page.locator('.link-playback tbody tr')).toHaveCount(2)
  await expect(page.locator('.link-playback th')).toHaveText(['时间', '上游', 'UA', '结果', '目标', '客户端 IP', '缓存状态', '缓存有效期', '耗时'])
  await page.getByRole('button', { name: '筛选播放类型', exact: true }).click()
  await page.getByRole('option', { name: '音频适配', exact: true }).click()
  await expect(page.locator('.link-playback tbody tr')).toHaveCount(1)
  await expect(page.locator('.link-playback tbody')).toContainText('proxy-book.wma')
  await page.screenshot({ path: info.outputPath('playback-desktop.png'), fullPage: true })
  await page.unroute('**/api/link-playback')
  await page.route('**/api/link-playback', route => route.fulfill({ json: { recentEvents: Array.from({ length: 1500 }, (_, i) => ({
    time: new Date().toISOString(), upstream: 'test', target: `https://example.com/a-long-media-directory-for-overflow/book-${i}.m4a`, outcome: 'transcode', client: '192.168.1.2', userAgent: 'iOS', cacheSource: 'restored', cacheTtlSeconds: 7200, durationMs: 20000000
  })) } }))
  await page.getByRole('button', { name: '刷新播放流水', exact: true }).click()
  await expect(page.locator('.playback-count')).toHaveText('共 1500 条')
  await expect(page.locator('.playback-event').first()).toContainText('2 h')
  expect(await page.locator('.playback-event').count()).toBeLessThanOrEqual(40)
  await page.locator('.playback-scroller').evaluate(el => { el.scrollTop = 26000 })
  await expect(page.locator('.playback-event').first()).not.toContainText('book-0.m4a')
  await page.locator('.playback-scroller').evaluate(el => { el.scrollTop = el.scrollHeight })
  await page.waitForTimeout(400)
  const bottom = await page.locator('.playback-scroller').evaluate(el => ({ top: el.scrollTop, height: el.scrollHeight }))
  await page.locator('.playback-scroller').hover()
  for (let i = 0; i < 8; i++) { await page.mouse.wheel(0, 700); await page.waitForTimeout(70) }
  const afterBottom = await page.locator('.playback-scroller').evaluate(el => ({ top: el.scrollTop, height: el.scrollHeight }))
  expect(Math.abs(bottom.top - afterBottom.top)).toBeLessThan(2)
  expect(bottom.height).toBe(afterBottom.height)
  await page.getByLabel('搜索播放流水', { exact: true }).fill('book-1499')
  await expect(page.locator('.playback-event')).toHaveCount(1)
  await expect(page.locator('.playback-event')).toContainText('恢复命中')
  await expect(page.locator('.playback-event')).toContainText('20 ms')
  await expect(page.locator('.playback-event td').first()).toHaveText(/^\d{2}\/\d{2} \d{2}:\d{2}:\d{2}$/)
  await page.evaluate(() => {
    Object.defineProperty(navigator, 'clipboard', { configurable: true, value: undefined })
    window.copiedFallback = []
    document.execCommand = command => { if (command === 'copy') window.copiedFallback.push(document.activeElement.value); return command === 'copy' }
  })
  const copyButtons = page.locator('.playback-event .playback-copy')
  await copyButtons.nth(0).hover()
  await page.waitForTimeout(450)
  await expect(page.getByRole('tooltip')).toHaveCount(0)
  for (let i = 0; i < 3; i++) await copyButtons.nth(i).click()
  expect(await page.evaluate(() => window.copiedFallback)).toEqual(['iOS', 'https://example.com/a-long-media-directory-for-overflow/book-1499.m4a', '192.168.1.2'])
  await copyButtons.nth(1).hover()
  await expect(page.getByRole('tooltip')).toContainText('book-1499.m4a')
  await expect(page.getByRole('tooltip')).toHaveCSS('border-radius', '10px')
  expect(await page.locator('.playback-count').evaluate(el => Math.abs(innerHeight - el.getBoundingClientRect().bottom))).toBeLessThanOrEqual(10)
  await page.unroute('**/api/link-playback')
  await page.getByRole('link', { name: '以链管理', exact: true }).click()
  await expect(page).toHaveURL(/\/links\/manage$/)
  await page.screenshot({ path: info.outputPath('links-desktop.png'), fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: info.outputPath('links-mobile.png'), fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('link', { name: '直链缓存', exact: true }).click()
  await expect(page.getByText('暂无播放记录', { exact: true })).toBeVisible()
  await page.goto('/settings/logs')
  await expect(page.getByLabel('日志保留天数', { exact: true })).toHaveValue('15')
  await expect(page.getByLabel('日志条数上限', { exact: true })).toHaveValue('20000')
  await page.getByLabel('日志保留天数', { exact: true }).fill('20')
  await page.getByRole('button', { name: '保存设置', exact: true }).click()
  await expect(page.locator('.toast').filter({ hasText: '设置已保存' })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('日志保留天数', { exact: true })).toHaveValue('20')
  await page.goto('/files')
  await expect(page.getByRole('button', { name: 'Movies', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Movies', exact: true }).dblclick()
  await page.getByLabel('搜索当前目录', { exact: true }).fill('Arrival')
  await expect(page.getByRole('button', { name: 'sample.mp4', exact: true })).toBeVisible()
  await page.getByLabel('搜索当前目录', { exact: true }).press('Enter')
  await expect(page.getByRole('button', { name: 'sample.mp4', exact: true })).toHaveCount(0)
  await page.getByLabel('搜索当前目录', { exact: true }).fill('')
  await page.getByLabel('搜索当前目录', { exact: true }).press('Enter')
  await page.getByRole('button', { name: '展开收藏栏', exact: true }).click()
  await page.getByRole('button', { name: '收藏当前目录', exact: true }).click()
  await expect(page.getByRole('complementary', { name: '目录收藏' })).toContainText('Movies')
  await page.getByRole('navigation', { name: '文件路径' }).getByRole('button', { name: '根目录', exact: true }).click()
  await expect(page.getByRole('button', { name: '收藏当前目录', exact: true })).toBeDisabled()
  await expect(page.locator('.page-foot')).toHaveCount(0)
  await page.getByRole('complementary', { name: '目录收藏' }).getByRole('button', { name: 'Movies', exact: true }).click()
  await page.getByRole('button', { name: '当前列表视图，切换网格', exact: true }).click()
  await expect(page.locator('.file-grid-item')).toHaveCount(2)
  await page.screenshot({ path: info.outputPath('files-grid-mobile.png'), fullPage: true })
  await page.reload()
  await expect(page.getByRole('button', { name: '当前网格视图，切换列表', exact: true })).toBeVisible()
  await page.getByRole('complementary', { name: '目录收藏' }).getByRole('button', { name: 'Movies', exact: true }).click()
  await expect(page.locator('.file-grid-item')).toHaveCount(2)
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.screenshot({ path: info.outputPath('files-grid-desktop.png'), fullPage: true })
  await page.goto('/tools')
  await page.getByRole('button', { name: /^配置备份/ }).click()
  await expect(page.getByRole('dialog')).toContainText('密码加密')
  await page.getByRole('button', { name: '导出配置备份', exact: true }).click()
  await page.getByLabel('备份密码', { exact: true }).fill('backup-test')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: '确认导出', exact: true }).click()
  expect((await download).suggestedFilename()).toMatch(/^aether-config-.*\.aether$/)
})
