import { test, expect } from '@playwright/test'
import { readFileSync } from 'node:fs'
import { createHash } from 'node:crypto'
import path from 'node:path'

test('local CAS generation and persisted named directory navigation', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByLabel('账号', { exact: true }).fill('my-aether-owner')
  await page.getByLabel('密码', { exact: true }).fill('a1')
  await page.getByRole('button', { name: '登录工作空间', exact: true }).click()
  await page.getByRole('link', { name: '任务管理', exact: true }).click()
  await page.getByRole('link', { name: 'CAS 任务', exact: true }).click()
  await page.getByRole('button', { name: '添加任务', exact: true }).click()
  await page.getByLabel('任务名称').fill('本地 CAS 哈希')
  await expect(page.getByRole('button', { name: '绑定存储', exact: true })).toContainText('选择移动或天翼存储')
  await expect(page.getByRole('button', { name: '选择目录', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: '保存任务', exact: true })).toBeDisabled()
  const name = await page.getByLabel('任务名称').boundingBox()
  const binding = await page.getByRole('button', { name: '绑定存储', exact: true }).boundingBox()
  expect(binding.y).toBe(name.y)
  expect(binding.x).toBeGreaterThan(name.x)
  await page.getByRole('button', { name: '绑定存储', exact: true }).click()
  await page.getByRole('option', { name: 'CAS 天翼个人云', exact: true }).click()
  await page.getByRole('button', { name: '选择目录', exact: true }).click()
  await expect(page.locator('.source-accounts')).toContainText('天翼')
  await expect(page.locator('.source-accounts')).not.toContainText('移动')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '绑定存储', exact: true }).click()
  await page.getByRole('option', { name: 'CAS 测试个人云', exact: true }).click()
  const inputBox = await page.getByLabel('任务名称').boundingBox()
  const selectBox = await page.getByRole('button', { name: '生成方式', exact: true }).boundingBox()
  expect(selectBox.height).toBe(inputBox.height)
  await expect(page.getByRole('dialog')).toHaveCSS('scrollbar-width', 'none')
  await expect(page.getByRole('button', { name: 'CAS 操作', exact: true })).toHaveCount(0)
  await page.getByLabel('生成目录', { exact: true }).fill('local-cas')
  await page.getByRole('button', { name: '选择目录', exact: true }).click()
  await page.locator('.source-accounts').getByRole('button', { name: /家庭影音库/ }).click()
  await page.getByRole('dialog', { name: '选择存储目录' }).getByRole('button', { name: 'Movies', exact: true }).click()
  await page.getByRole('button', { name: '选择当前目录', exact: true }).click()
  await expect(page.locator('.source-trigger')).toContainText('Movies')
  await expect(page.getByLabel('还原文件保留时间', { exact: true })).toHaveValue('12')
  await page.screenshot({ path: testInfo.outputPath('local-cas-form.png'), fullPage: true })
  await page.getByRole('button', { name: '保存任务', exact: true }).click()
  const row = page.locator('.task-row-card').filter({ hasText: '本地 CAS 哈希' })
  await row.getByRole('button', { name: '立即执行', exact: true }).click()
  await expect.poll(async () => {
    const state = await (await page.request.get('/api/state')).json()
    return state.tasks.find(t => t.name === '本地 CAS 哈希')?.status
  }).toBe('success')
  const output = readFileSync(path.join(process.env.AETHER_E2E_ROOT, 'data', 'strm', 'local-cas', 'Arrival.MP4.cas'), 'utf8')
  const info = JSON.parse(Buffer.from(output, 'base64').toString('utf8'))
  expect(info.sha256).toBe(createHash('sha256').update('test-video-content').digest('hex'))
  expect(info.provider).toBe('mobile')
  expect(info.md5).toBe(createHash('md5').update('test-video-content').digest('hex'))
  expect(info.playback_url).toContain('/stream/')
  await page.reload()
  await row.getByRole('button', {name:'任务操作 本地 CAS 哈希',exact:true}).click()
  await row.getByRole('button', { name: '编辑任务', exact: true }).click()
  await expect(page.locator('.source-trigger')).toContainText('Movies')
  await page.getByRole('button', { name: '选择目录', exact: true }).click()
  await expect(page.locator('.source-path')).toHaveText('Movies')
  await page.getByRole('button', { name: '上级目录', exact: true }).click()
  await expect(page.locator('.source-path')).toHaveText('根目录')
})
