import { test, expect } from '@playwright/test'
import { writeFileSync, mkdirSync } from 'node:fs'
import path from 'node:path'

test('compact desktop, card menus, file actions and encrypted import', async ({ page }, info) => {
  test.setTimeout(150000)
  await page.goto('/')
  for (const [width, height] of [[1920,1080],[1366,768],[1280,600],[1024,600],[800,480]]) {
    await page.setViewportSize({ width, height })
    await expect(page.getByRole('button', { name: '登录工作空间', exact: true })).toBeVisible()
    expect(await page.locator('.login-form').evaluate(el => {
      const side = el.closest('.login-form-side'), form = el.getBoundingClientRect()
      return form.width <= side.clientWidth && document.documentElement.scrollWidth <= innerWidth
    })).toBe(true)
    await page.getByRole('button', { name: '登录工作空间', exact: true }).scrollIntoViewIfNeeded()
    await page.screenshot({ path: info.outputPath(`login-${width}-${height}.png`), fullPage: true })
  }
  await page.setViewportSize({ width: 1366, height: 768 })
  await page.getByLabel('账号', { exact: true }).fill('my-aether-owner')
  await page.getByLabel('密码', { exact: true }).fill('a1')
  const login = page.waitForResponse(res => res.url().endsWith('/api/auth/login'))
  await page.getByRole('button', { name: '登录工作空间', exact: true }).click()
  if ((await login).status() === 429) {
    await page.waitForTimeout(61000)
    await page.getByRole('button', { name: '登录工作空间', exact: true }).click()
  }
  await expect(page.getByRole('navigation', { name: '主导航' })).toBeVisible()
  await page.goto('/storage')
  const card = page.locator('.storage-card').filter({ hasText: '家庭影音库' })
  await card.click({ button: 'right' })
  await expect(card.locator('.storage-menu button')).toHaveText(['编辑存储','测试连接','停用存储','删除存储'])
  await page.keyboard.press('Escape')
  await card.locator('h3').click()
  await expect(page.getByRole('dialog', { name: '编辑存储池' })).toBeVisible()
  expect(await page.getByRole('dialog').evaluate(el => {
    const input = el.querySelector('input:not([type=checkbox])'), select = el.querySelector('.rounded-select-trigger')
    return input.getBoundingClientRect().height === select.getBoundingClientRect().height
  })).toBe(true)
  await page.keyboard.press('Escape')
  await page.goto('/links')
  await page.locator('.link-card').first().click({ button:'right' })
  await expect(page.locator('.context-menu button')).toHaveText(['编辑以链','测试连接','启用链接','删除链接'])
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: '添加以太链接', exact: true }).click()
  await page.getByRole('button', { name: 'Emby', exact: true }).click()
  await expect(page.getByLabel('反代端口', { exact: true })).toHaveValue('')
  await page.keyboard.press('Escape')
  const media = path.join(process.env.AETHER_E2E_ROOT,'media')
  mkdirSync(path.join(media,'Operations'),{recursive:true})
  writeFileSync(path.join(media,'Operations','one.txt'),'one')
  writeFileSync(path.join(media,'Operations','two.txt'),'two')
  await page.goto('/files')
  await page.getByRole('button', { name:'刷新目录',exact:true }).click()
  if (await page.getByRole('button', { name:'当前网格视图，切换列表',exact:true }).isVisible()) await page.getByRole('button', { name:'当前网格视图，切换列表',exact:true }).click()
  await page.getByRole('button',{name:'Operations',exact:true}).dblclick()
  await page.getByRole('button',{name:'one.txt',exact:true}).click()
  await page.keyboard.press('F2')
  await page.getByLabel('新名称',{exact:true}).fill('renamed.txt')
  await page.getByLabel('新名称',{exact:true}).press('Enter')
  await expect(page.getByRole('button',{name:'renamed.txt',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'renamed.txt',exact:true}).click()
  await page.getByRole('button',{name:'two.txt',exact:true}).click({modifiers:['Shift']})
  await page.getByRole('button',{name:'two.txt',exact:true}).click({button:'right'})
  await expect(page.locator('.context-menu button')).toHaveText(['移动到','复制到','删除'])
  await page.getByRole('button',{name:'复制到',exact:true}).click()
  await page.getByRole('button',{name:'选择当前目录',exact:true}).click()
  await expect(page.locator('.toast').filter({hasText:'文件操作完成'})).toBeVisible()
  await page.getByRole('button',{name:'名称',exact:true}).click()
  await expect(page.locator('th').first()).toHaveAttribute('aria-sort','descending')
  await page.screenshot({path:info.outputPath('file-actions.png'),fullPage:true})
  await page.goto('/settings/about')
  await page.screenshot({path:info.outputPath('about-1366.png'),fullPage:true})
  expect(await page.locator('.about-actions').evaluate(el=>el.getBoundingClientRect().bottom <= innerHeight)).toBe(true)
  await page.goto('/tools')
  await expect(page.locator('.plugin-card').last()).toContainText('配置备份')
  await page.getByRole('button',{name:/^配置备份/}).click()
  await page.getByRole('button',{name:'导出配置备份',exact:true}).click()
  await page.getByLabel('备份密码',{exact:true}).fill('test-import-password')
  const download = page.waitForEvent('download')
  await page.getByRole('button',{name:'确认导出',exact:true}).click()
  const file=info.outputPath('backup.aether'); await (await download).saveAs(file)
  await page.getByRole('button',{name:/^配置备份/}).click()
  await page.getByRole('button',{name:'导入配置备份',exact:true}).click()
  await page.getByLabel('选择备份文件').setInputFiles(file)
  await page.getByRole('button',{name:'下一步',exact:true}).click()
  await page.getByLabel('备份密码',{exact:true}).fill('incorrect')
  await page.getByRole('button',{name:'确认导入',exact:true}).click()
  await expect(page.locator('.toast').filter({hasText:'密码错误'})).toBeVisible()
  await page.getByLabel('备份密码',{exact:true}).fill('test-import-password')
  await page.getByRole('button',{name:'确认导入',exact:true}).click()
  await expect(page.locator('.toast').filter({hasText:'重启容器生效'})).toBeVisible()
})
