<script setup>
import { computed } from 'vue'
import { state, bytes, date } from '../lib'
import Icon from '../components/Icon.vue'
const hitRate = computed(() => { const n = (state.cache.hits || 0) + (state.cache.misses || 0); return n ? Math.round(state.cache.hits / n * 100) : 0 })
</script>
<template>
  <section class="page-head"><div><div class="eyebrow">WORKSPACE OVERVIEW</div><h1>以太概览<span class="title-dot">.</span></h1><p>存储、文件与任务，尽在掌握。</p></div><span class="status success"><i />服务运行中</span></section>
  <div class="metric-strip"><div><span class="metric-icon"><Icon name="Layers3" /></span><span><small>已添加存储</small><strong>{{ state.storages.length }}<em>个</em></strong></span></div><div><span class="metric-icon green"><Icon name="Activity" /></span><span><small>运行中任务</small><strong>{{ state.tasks.filter(t => t.status === 'running').length }}<em>项</em></strong></span></div><div><span class="metric-icon amber"><Icon name="Database" /></span><span><small>缓存命中率</small><strong>{{ hitRate }}<em>%</em></strong></span></div><div><span class="metric-icon neutral"><Icon name="Download" /></span><span><small>本次运行下载量</small><strong class="text-metric">{{ bytes(state.traffic.downloaded) }}</strong></span></div></div>
  <div class="dashboard-grid"><section><div class="section-label"><h2>存储连接</h2><button class="text-btn" @click="$router.push('/storage')">管理存储<Icon name="ArrowRight" :size="15" /></button></div><div v-if="!state.storages.length" class="empty-state compact"><Icon name="Cloud" :size="36" /><h3>连接你的第一个存储空间</h3><button class="btn primary" @click="$router.push('/storage')"><Icon name="Plus" />添加存储池</button></div><div v-for="s in state.storages" :key="s.id" class="summary-row"><span>{{ s.name }}</span><span class="status" :class="s.status === 'connected' ? 'success' : 'pending'">{{ s.status === 'connected' ? '已连接' : '待连接' }}</span></div></section><section><div class="section-label"><h2>运行状态</h2><Icon name="Activity" /></div><div class="summary-row"><span>服务运行时间</span><strong>{{ Math.floor(state.uptime / 3600) }} 时 {{ Math.floor(state.uptime % 3600 / 60) }} 分</strong></div><div class="summary-row"><span>元数据缓存</span><strong>{{ state.cache.entries || 0 }} 条 / {{ bytes(state.cache.bytes) }}</strong></div><div class="summary-row"><span>WebDAV 服务</span><span class="status" :class="state.settings.webdavEnabled ? 'success' : 'muted'">{{ state.settings.webdavEnabled ? '已启用' : '未启用' }}</span></div><div class="summary-row"><span>服务端口</span><code>15151</code></div></section></div>
  <section class="activity-section"><div class="section-label"><h2>最近活动</h2><button class="text-btn" @click="$router.push('/logs')">全部日志<Icon name="ArrowRight" :size="15" /></button></div><p v-if="!state.logs.length" class="small-empty">暂无活动记录</p><div v-for="(log, i) in state.logs.slice(-6).reverse()" :key="i" class="activity-row"><span class="activity-dot" /><span>{{ log.message }}</span><time>{{ date(log.time) }}</time></div></section>
</template>
